apollographql/apollo-tooling

src/swift/codeGeneration.js, test/swift/codeGeneration.js
These are needed for access from outside of Swift module
=> Add empty public inits for Swift classes 

src/typescript/language.js, test/typescript/codeGeneration.js
Described in:
https://github.com/apollostack/apollo-codegen/pull/5#issuecomment-264817132
@rricard
=> [TypeScript] Fixed a bug with inline fragment array

src/cli.js, src/generate.js, src/typescript/codeGeneration.js, src/typescript/index.js, src/typescript/language.js, src/typescript/types.js, test/typescript/codeGeneration.js
This is a work in progress targeting TS type annotation generation. For now, only basic structures will be generated.
=> TypeScript Code generation

src/typescript/codeGeneration.js, src/typescript/language.js, test/typescript/codeGeneration.js
I may have mishandled (maybe via a wrong rebase) the commits in the PRs #17 and #18. I just reapplied @dotansimha patches here, so thanks to him!
Fixes #19
=> Reapply diffs from two PRs

src/cli.js, src/flow/codeGeneration.js, src/flow/index.js, src/flow/language.js, src/flow/types.js, src/generate.js, test/flow/codeGeneration.js
Mainly copy-pasta from typescript, only the nullables changes...
Fixes #2
=> Basic flow support

src/flow/codeGeneration.js
Port of the Typescript fix f238eba (issue #28)
=> Fixes non-null arrays in Flow codegen

src/flow/language.js, src/typescript/language.js, test/flow/codeGeneration.js, test/starwars/HeroAndFriends.graphql, test/typescript/codeGeneration.js
This fixes https://github.com/apollographql/apollo-codegen/issues/77 for both Typescript and Flow.
=> Fix bug with inconsistent fragment capitalization

package.json
Jest 20 got released over the weekend. PR to update
=> Bump Jest to v20

src/loading.js
addresses #25 
this is clearly very hap hazard, because regex is not the best tool for doing this job, but this should work for most simple cases, like:
```js
const Query = gql`
query Foo($id: String!) {
foo(fooId: $id) {
...BarFragment
}
}
${barFragment}
`
```
The alternative would be to use a different parser for ts/js/swift, but that's a much bigger effort
=> [feedback] add functionality to extract gql document from gql template

src/errors.ts, src/generate.ts, src/loading.ts, src/swift/codeGeneration.js
The goal behind this work is to provide IDE features while working on a code generator. We're not going to cover everything here but we'll at least provide enough so we can get help while writing features.
=> Type the common parts (entry points)

README.md, src/cli.js, src/generate.ts, src/loading.ts
Continuing @gajus' work on PR #120 by adding warning messages in the cli
and rebasing master.
=> feat: make tagname configurable (fixes #119)

README.md, test/validation.js
Adding documentation to the README for the change that accompanies #143.
=> Add documentation for requiring the __typename introspection field.

src/cli.js, src/generate.ts
closes https://github.com/apollographql/apollo-codegen/issues/174
=> Make merge-in-fields-from-fragment-spreads CLI configurable

src/flow/codeGeneration.js, src/typescript/codeGeneration.js, test/flow/__snapshots__/codeGeneration.js.snap, test/typescript/__snapshots__/codeGeneration.js.snap
Fixes #92 
Fixes #63 
Breaking Change
=> Remove forced pascal casing

src/flow/codeGeneration.js, src/flow/language.js, src/typescript/codeGeneration.js, src/typescript/language.js, test/flow/__snapshots__/codeGeneration.js.snap, test/flow/codeGeneration.js, test/typescript/__snapshots__/codeGeneration.js.snap, test/typescript/codeGeneration.js
=> Detect inner array elements that are nullable and mark them as nullable

src/flow/codeGeneration.js, src/typescript/codeGeneration.js, test/flow/__snapshots__/codeGeneration.js.snap, test/flow/codeGeneration.js, test/misc/schema.graphql, test/misc/schema.json, test/typescript/__snapshots__/codeGeneration.js.snap, test/typescript/codeGeneration.js
Replaced with the correct type name
Fixes #183
=> Top-line __typename is not a string anymore

src/typescript/codeGeneration.ts, test/typescript/__snapshots__/codeGeneration.js.snap
=> Use TypeScript string enums

README.md
=> Improve docs by describing the purpose of the commands

src/typescript/codeGeneration.ts
=> Do not enable tslint in auto-generated schema file

README.md
=> Fix markdown code-block typo

src/compiler/index.ts, src/generate.ts, src/swift/codeGeneration.ts
* Adds an optional operationId property to the Operation object
* Bug fix for #280
=> Fix Swift Operation Id Path 

src/javascript/typescript/__tests__/__snapshots__/codeGeneration.ts.snap, src/javascript/typescript/__tests__/codeGeneration.ts, src/javascript/typescript/language.ts, src/javascript/typescript/printer.ts
Fixes #306 for Typescript
Mirrors #311
=> Fix GraphQL multiline comment support for typescript-modern target

src/typescript/codeGeneration.ts, test/typescript/__snapshots__/codeGeneration.js.snap
=> Sort enums for cleaner diffs

src/flow/codeGeneration.js, src/javascript/flow/__tests__/__snapshots__/codeGeneration.ts.snap, src/javascript/flow/language.ts, src/javascript/typescript/__tests__/__snapshots__/codeGeneration.ts.snap, src/javascript/typescript/language.ts, src/typescript/codeGeneration.ts, src/utilities/graphql.ts, test/flow/__snapshots__/codeGeneration.js.snap
=> Sort GraphQL Enums for javascript targets

src/flow/codeGeneration.js, src/typescript/codeGeneration.ts, test/flow/__snapshots__/codeGeneration.js.snap, test/flow/codeGeneration.js, test/typescript/__snapshots__/codeGeneration.js.snap, test/typescript/codeGeneration.js
This is the fixed version of #294. The only difference is in commit c7d387f96140ec532519c4719b531a5ffebf00ca.
=> Add typeName for nested property objects

src/validation.ts, test/fixtures/starwars/UnknownDirective.graphql, test/validation.ts
=> Removed Unknown Directive Validation

package-lock.json, package.json, src/javascript/flow/__tests__/__snapshots__/codeGeneration.ts.snap
=> [ts-modern] Upgrading @babel/types and @babel/generator to 7.0.0-beta.38

src/javascript/flow/language.ts, src/javascript/typescript/language.ts, test/fixtures/misc/schema.json, test/flow/__snapshots__/codeGeneration.js.snap, test/typescript/__snapshots__/codeGeneration.js.snap
I believe the title says it all.
=> handle more than one line break in comments

src/flow/types.js
This is fix for #375 
Should I add test for it? (I couldn't find test about `options` of Flow generator....)
=> Fix unhandled passthroughCustomScalars option in Flow generator

CHANGELOG.md, packages/apollo-codegen-core/src/polyfills.ts, packages/apollo-codegen-core/src/utilities/array.ts, packages/apollo-codegen/package.json
=> Use corejs polyfill for Array.flatMap

.travis.yml
Eliminates duplication when creating PRs based on other branches.
=> Only run Travis builds on master and PRs

packages/apollo-cli/src/commands/codegen/generate.ts, packages/apollo-cli/src/commands/schema/checkQueries.ts
=> Handle bash expansions for the queries argument

package-lock.json, package.json
=> Add lerna-changelog to manage generating changelogs

package-lock.json, packages/apollo-cli/package.json, packages/apollo-codegen-core/package.json, packages/apollo-codegen-flow-legacy/package.json, packages/apollo-codegen-flow/package.json, packages/apollo-codegen-scala/package.json, packages/apollo-codegen-swift/package.json, packages/apollo-codegen-typescript-legacy/package.json, packages/apollo-codegen-typescript/package.json
=> Run `build` before publishing to prevent uploading stale code

packages/apollo-cli/src/commands/codegen/__tests__/__snapshots__/generate.test.ts.snap, packages/apollo-cli/src/commands/codegen/__tests__/generate.test.ts, packages/apollo-cli/src/commands/codegen/generate.ts, packages/apollo-cli/src/fetch-schema.ts
=> Support generating based on .graphql schema files

packages/apollo-cli/src/commands/codegen/__tests__/__snapshots__/generate.test.ts.snap, packages/apollo-cli/src/commands/codegen/__tests__/generate.test.ts, packages/apollo-cli/src/commands/codegen/generate.ts, packages/apollo-cli/src/fetch-schema.ts
=> Support loading server-side schema from JS/TS files

packages/apollo-cli/src/commands/codegen/__tests__/__snapshots__/generate.test.ts.snap, packages/apollo-cli/src/commands/codegen/__tests__/fixtures/clientSideSchema.graphql, packages/apollo-cli/src/commands/codegen/__tests__/fixtures/clientSideSchemaQuery.graphql, packages/apollo-cli/src/commands/codegen/__tests__/generate.test.ts, packages/apollo-codegen-core/src/compiler/index.ts
=>  Handle cases when storing server-defined models in local state

packages/apollo-cli/src/generate.ts
=> Assume the output is a directory when it has no extension

package-lock.json, packages/apollo-cli/@types/gaze.d.ts, packages/apollo-cli/package.json, packages/apollo-cli/src/commands/codegen/generate.ts
=> Support file watching for codegen:generate

packages/apollo-cli/src/commands/codegen/__tests__/generate.test.ts, packages/apollo-cli/src/commands/schema/__tests__/publish.test.ts, packages/apollo-cli/tsconfig.json, tsconfig.base.json
=> Make TypeScript options more consistent across packages

.travis.yml
=> Only check queries when API key is available

.travis.yml
=> Attempt 2 at skipping query checks in PR builds

packages/apollo-cli/src/config.ts, packages/apollo-language-server/src/workspace.ts, packages/apollo-vscode/package-lock.json
=>  [VSCode] Fix detection of projects inside folders

packages/apollo-cli/README.md, packages/apollo-cli/package.json
=> Fixed broken command links

packages/apollo-cli/src/commands/codegen/__tests__/__snapshots__/generate.test.ts.snap, packages/apollo-cli/src/generate.ts, packages/apollo-codegen-typescript/src/__tests__/__snapshots__/codeGeneration.ts.snap, packages/apollo-codegen-typescript/src/printer.ts
=> [TS] Elimate newlines at beginning of file and add newline at end of file

packages/apollo-language-server/copy-apollo-libs.sh, packages/apollo-language-server/src/languageProvider.ts, packages/apollo-language-server/src/project.ts, packages/apollo-language-server/src/server.ts, packages/apollo-language-server/src/workspace.ts, packages/apollo-vscode/src/extension.ts
=> Display status of loading tasks for config and Engine stats

.circleci/config.yml, package-lock.json
Also removes npm circle from query check Job
=> Query Check Circle CI uses `npm ci`

packages/apollo-vscode/package-lock.json, packages/apollo-vscode/package.json, packages/apollo-vscode/src/StatusBar.ts, packages/apollo-vscode/src/extension.ts
This PR adds a status bar item to the VSCode extension. It has a loading / loaded state.
Included some named import cleanup as well.
=> Add status bar item to extension

packages/apollo/README.md
=> Add docs on how to use lerna-changelog when publishing

packages/apollo/README.md
One backtick too much, one quote too little :) -> Fixed.
**Pull Request Labels**
While not necessary, you can help organize our pull requests by labeling this issue when you open it.  To add a label automatically, simply [x] mark the appropriate box below:
To add a label not listed above, simply place `/label another-label-name` on a line by itself.
=> Fix README Syntax Highlighting

packages/apollo/README.md
=> Fix missing comma in basic config example

packages/vscode-apollo/README.md
Update a broken link and move the config link into the configuration section
Fixes #708
=> Update link in VS Code README

packages/apollo-language-server/src/schema/providers/file.ts
=> Fix "go to definition" when a local schema file is provided

.github/CODEOWNERS, packages/apollo/README.md
Clearly identify repo maintainers.
=> Set GH CODEOWNERS and update the README

packages/apollo/src/generate.ts
Patch for #810 
- Fix mkdir error i mentioned in #810 on windows
=> Correct path build for windows

.github/ISSUE_TEMPLATE/bug.md, .github/ISSUE_TEMPLATE/feature-request.md, .github/ISSUE_TEMPLATE/question-discussion.md, .github/PULL_REQUEST_TEMPLATE.md
Just to make our lives a little easier, I figured I'd copy and modify the issue/PR templates from other repos that we have :)
=> Add Issue and PR Templates

CHANGELOG.md
resolves #593
My eyes are bleeding from reading commits
=> Backfill changelog with previous releases

package-lock.json, packages/apollo/package.json, renovate.json
Renovate updated oclif/config. Pin to previous working version.
=> Re-pin oclif/config, regenerate package-lock.json

package-lock.json, packages/apollo-language-server/src/config/__tests__/config.ts, packages/apollo-language-server/src/config/__tests__/utils.ts, packages/apollo-language-server/src/config/config.ts, packages/apollo-language-server/src/config/utils.ts, packages/apollo/src/commands/client/__tests__/generate.test.ts
=> [WIP] Test config

packages/apollo/src/commands/client/codegen.ts
=> updated inline code docs for codegen

.circleci/config.yml, .prettierignore, CHANGELOG.md, package-lock.json, package.json, packages/apollo-language-server/globalTypes.ts, packages/apollo-language-server/src/config/utils.ts, packages/apollo-language-server/src/engine/GraphQLDataSource.ts, packages/apollo-language-server/src/engine/index.ts, packages/apollo-language-server/src/engine/operations/checkSchema.ts, packages/apollo-language-server/src/engine/operations/registerOperations.ts, packages/apollo-language-server/src/engine/operations/schemaTagInfo.ts, packages/apollo-language-server/src/engine/operations/schemaTagsAndFieldStats.ts, packages/apollo-language-server/src/engine/operations/uploadSchema.ts, packages/apollo-language-server/src/engine/operations/validateOperations.ts, packages/apollo-language-server/src/graphqlTypes.ts, packages/apollo-language-server/src/index.ts, packages/apollo-language-server/src/project/client.ts, packages/apollo-language-server/src/schema/providers/engine.ts, packages/apollo/src/commands/client/check.ts, packages/apollo/src/commands/service/check.ts, packages/apollo/src/commands/service/info.ts, packages/apollo/src/commands/service/push.ts, packages/apollo/src/utils/validateHistoricParams.ts
This PR serves a couple purposes:
1) Get more reliable Typescript types by using code generation and CI to ensure our types stay up to date with our schema
2) Dogfood codegen (on its own codebase 😄)
TODO:
=> Use generated Typescript types

CHANGELOG.md, packages/apollo-language-server/src/utilities/source.ts
=> Re-add modified visitWithTypeInfo to fix hover

CHANGELOG.md, packages/vscode-apollo/src/languageServerClient.ts
=> Add env variable to silence tls errors

CHANGELOG.md, packages/vscode-apollo/syntaxes/graphql.json
Add support for single quote comments in the textmate syntax.
Fixes #848
TODO:
=> Permit single quote, single line descriptions

package-lock.json, package.json, renovate.json
This commit downgrades and pins lerna to the previous minor. Thanks
to @abernix for mentioning an issue he discovered while using the
`prerelease` functionality. More details pending further
investigation, but for now this will work fine and prevent partial
publishes that @abernix encountered.
TODO:
=> Downgrade lerna

CHANGELOG.md, packages/apollo-language-server/src/engine/operations/checkPartialSchema.ts, packages/apollo-language-server/src/engine/operations/removeServiceAndCompose.ts, packages/apollo-language-server/src/engine/operations/uploadAndComposePartialSchema.ts, packages/apollo-language-server/src/graphqlTypes.ts, packages/apollo/src/commands/service/check.ts, packages/apollo/src/commands/service/delete.ts, packages/apollo/src/commands/service/push.ts
Thanks to @caydie-tran for handing this off to me. LGTM!
TODO:
=> Remove federation warnings and update types

CHANGELOG.md, packages/apollo-language-server/src/engine/operations/checkPartialSchema.ts, packages/apollo-language-server/src/graphqlTypes.ts, packages/apollo/src/commands/service/__tests__/__snapshots__/check.test.ts.snap, packages/apollo/src/commands/service/__tests__/check.test.ts, packages/apollo/src/commands/service/check.ts
add the graph composition id to the returned url from the cli so the UI can add service name
TODO:
=> Graph Composition ID included in targetURL

packages/apollo/src/commands/service/delete.ts, packages/apollo/src/commands/service/push.ts
Use --serviceName like everywhere else. Also deprecate the --federated
flag.
TODO:
=> Do not require `--federated` for service:delete

packages/apollo/src/commands/service/__tests__/check.test.ts, packages/apollo/src/commands/service/__tests__/list.test.ts
=> Fix CI? - Extend jest timeout

packages/apollo/README.md, packages/apollo/src/commands/client/codegen.ts, packages/apollo/src/commands/service/check.ts, packages/apollo/src/commands/service/push.ts
=> Update flag descriptions for multiple localSchemaFiles

packages/apollo-codegen-core/src/utilities/graphql.ts, packages/apollo-language-server/src/utilities/graphql.ts
TODO:
**I have not added an entry to the changelog as this change seems rather trivial. Please let me know if you want me to add one.**
=> Remove unreachable code

packages/apollo/README.md
- Fixed wrong link markdown 
- Changed a link to "other Node debugger" as it's more relevant. 
TODO:
=> Fix a wrong markdown in README

CHANGELOG.md, packages/apollo-codegen-swift/src/__tests__/codeGeneration.ts, packages/apollo-codegen-swift/src/helpers.ts
Also add a test that covers all scalar types just in case.
Fixes #1592
TODO:
=> swift: Fix code generation for null input fields

packages/apollo/README.md
=> README: Update links to config documentation

CHANGELOG.md, packages/apollo-codegen-flow/src/__tests__/__snapshots__/codeGeneration.ts.snap, packages/apollo-codegen-flow/src/codeGeneration.ts, packages/apollo-codegen-scala/src/__tests__/__snapshots__/codeGeneration.ts.snap, packages/apollo-codegen-scala/src/codeGeneration.ts, packages/apollo-codegen-swift/src/codeGeneration.ts, packages/apollo-codegen-typescript/src/__tests__/__snapshots__/codeGeneration.ts.snap, packages/apollo-codegen-typescript/src/codeGeneration.ts, packages/apollo/src/commands/client/__tests__/__snapshots__/generate.test.ts.snap
=> Add @generated comment to generated files

packages/apollo-language-server/src/graphqlTypes.ts, packages/apollo/src/commands/service/check.ts
=> Update generated types using `npm run client:codegen`.

packages/apollo-language-server/src/graphqlTypes.ts
=> chore(apollo): Update codegen types

packages/apollo/README.md
=> Add prerelease env var to publishing instructions

package-lock.json
For good measure.
Ref: https://github.com/apollographql/apollo-tooling/issues/2304
=> chore(deps): Update nested `es-abstract` deps to v1.18.0

CHANGELOG.md, package.json, src/language-server/__tests__/fileSet.test.ts, src/language-server/fileSet.ts
Fixes: https://github.com/apollographql/apollo-tooling/issues/1061.
TODO:
=> [apollo-language-server] Improve performance for FileSet#includesFile

.circleci/config.yml
Ref: https://github.com/apollographql/CircleCI-Orbs/pull/5
=> chore(deps) bump circleci orb apollo/oss-ci-cd-tooling to 0.0.20

package-lock.json, package.json, packages/apollo-language-server/src/server.ts
=> npm audit fix + some manual removals
