apollographql/apollo-tooling

src/downloadSchema.js, src/loading.js
Simply, modifies downloadSchema to keep the `data` field when storing the schema file to disk. An error is now thrown if `data` isn't the top-level field in the response.
As far as loading the schema for code-generation goes, an error is thrown when neither `data` nor `schema` exist as the top-level field. The reasoning is so as not break the old code-gen behaviour but I can modify that to only check for `data`.
Closes #8.
=> keep the data field when storing and loading the schema

src/typescript/codeGeneration.js
@rricard 
Can't add quick unit tests because the star wars schema does not have non-camelcased properties that I can add quick test for. 
Verified it against the GitHunt schema and it works.
https://github.com/apollostack/apollo-codegen/pull/5
=> [TypeScript] Fixed bug with camelCased propertyName

src/swift/codeGeneration.js, src/swift/types.js, test/swift/types.js
Hi,
I've found that if the GraphQL field names are not camel cased then the variables mapping is wrong:
Current code (wrong):
```
public var variables: GraphQLMap? {
return ["userId": userId]
}
```
Fixed code (correct):
```
public var variables: GraphQLMap? {
return ["user_id": userId]
}
```
This patch fixes the issue.
Also, Javascript floats are double precision, so I believe the correct mapping to Swift should be a Double instead of a Float. An update to the mapping fixes this.
=> Fix variables map to use field name instead of camel cased name / Use Double for GraphQLFloat.

src/typescript/codeGeneration.js, test/typescript/codeGeneration.js
Excluding files in TSLint via `tslint.json` is not supported and when using this tool TSLint may fail because of incompatibility.
Auto-generated code shouldn't pass thru TSLint so this change adds `tslint-disable` statement to the generated file and makes it safe to use with any TSLint configuration.
=> Disable tslint in generated file

src/cli.js, src/downloadSchema.js
Currently the tools is failing to download the schema if the server is
running on https with self-signed certificate. This changes adds a new
options (`skipSsl` alias `K` as in curl) that ignores invalid server
certificates.
=> Add an option to allow ‘insecure’ requests to the server

src/typescript/codeGeneration.js, test/typescript/codeGeneration.js
It turned out that TypeScript generated files do not end with a new
line character. The issue lies in the fact that
`generator.printOnNewline()` method was used that accepts a string
parameter. If the string is `falsy` it does nothing. The fix is to use
`printNewline()` method instead.
The tests were passing because the tag helper `stripIndent` is deleting
the new line charter when the line is ‘empty’. The tests are fixed by
appending the new line character to the expected value.
=> Fix new line at the end of TypeScript code generation

package.json, src/cli.js
On some environments (Windows or Mac) if `apollo-codegen` is invoked as
npm script it fails to expand the glob input pattern. The fix is to use
`glob` module and expand the paths in code.
You [this blog post](https://medium.com/@jakubsynowiec/you-should-always-quote-your-globs-in-npm-scripts-621887a2a784) for more info.
Closes #34
=> Use glob to expand paths if shell fails to do so

src/cli.js, src/flow/types.js, src/swift/types.js, src/typescript/types.js, test/swift/types.js
Builds on temporary `passthrough-custom-scalars`
=> Flag to define a prefix for custom scalars

src/swift/codeGeneration.js
Fix bug where empty Swift dictionaries should be '[:]' instead of empty string.
=> Fix bug where empty Swift dictionaries should be '[:]' instead of empty string.

README.md, src/cli.js, src/index.js, src/introspectSchema.js, test/introspectSchema.js, test/starwars/schema.graphql
Introduce a new command `introspect-schema` that will generate an
introspection JSON file based on a local GraphQL schema file.
This is useful if you need to generate `schema.json` without depending
on a running server for inspection.
=> Add a new command to generate introspection JSON from local schema

src/compilation.js, src/swift/codeGeneration.js, test/compilation.js, test/swift/codeGeneration.js
Fixes #65 
One remark is that it will always add the `possibleTypes` field to fragments, also when the `typeCondition` is not an abstract type. This adds some duplications in the IR representation.
=> Added possibleTypes of fragments to IR

src/flow/types.js, test/flow/codeGeneration.js, test/misc/schema.graphql, test/misc/schema.json
Currently custom scalars are annotated as `String` which is not a correct flow type.
This change uses the generic `any` type for all custom scalars when `passthrough-custom-scalars` is not used (which is broken for `--target flow` since the definitions of the passed through types aren't generated).
Ideally it should be possible to provide a map between custom scalars and flow types as discussed in https://github.com/apollographql/apollo-codegen/pull/53, but specific for each generation target or specify which type to use for all scalar types.
=> Use flow's `any` type for custom scalars instead of erroneous `String`

src/flow/language.js, src/utilities/CodeGenerator.js, test/flow/codeGeneration.js
This PR adds the Flow object spread + exact type definitions. 
https://github.com/apollographql/apollo-codegen/issues/62 is solved by this PR.
Fragment type intersections are replaced with multiple spreads within an exact object type - unions didn't seem to work with these.
Due to the use of the new object spread syntax, emitted code will break in any older version of flow.
=> Emit flow typedefs with exact brackets, fragment spreading

package.json, src/swift/naming.js
This not only improves the aesthetics of the generated property names, it actually fixes a compiler crash that could occur.
Take this initializer generated by version 0.11.0, for instance:
```swift
public init(values: [Any?]) {
Listing = values[0] as! Listing?
}
```
The problem is that the property name is the same as its type name (`Listing`), which results in a compiler crash. This could be solved be changing the generated code to use `self.Listing = ...`. However, if property names are lower-camel-cased and type names are upper-camel-cased (which is more Swift-y), this problem just goes away. Two 🐦 with one stone.
=> Make field property names Swift-y again

.babelrc, package.json, src/index.js, test/__snapshots__/compilation.js.snap, test/compilation.js, test/flow/__snapshots__/codeGeneration.js.snap, test/flow/codeGeneration.js, test/introspectSchema.js, test/swift/__snapshots__/codeGeneration.js.snap, test/swift/codeGeneration.js, test/swift/language.js, test/swift/types.js, test/typescript/__snapshots__/codeGeneration.js.snap, test/typescript/codeGeneration.js, test/validation.js, test/valueFromValueNode.js
Jest snapshots seems perfectly suited for the kinds of assertions apollo-codegen
does in it's tests. Issue described in more detail in #93.
It also has a more intuitive watch mode / interface that's pleasant to use.
Surprisingly after setting up a basic configuration, everything runs out of the box, yay.
=> Use Jest test runner

src/compilation.js, test/__snapshots__/compilation.js.snap, test/compilation.js
When a fragment is defined on a supertype, and it has inline fragments on subtypes, and that fragment is used in a context where the effective type does not match all of those subtypes, the compiler would incorrectly attempt to include fields from all of those spreads, and would fail.
This PR includes a test which crashes at first, and a follow-on commit which fixes the tests.
The following query illustrates the scenario:
```graphql
fragment CharacterFragment on Character {
... on Droid {
primaryFunction
}
... on Human {
height
}
}
query HumanAndDroid {
human(id: "human") {
...CharacterFragment
}
droid(id: "droid") {
...CharacterFragment
}
}
```
The compiler would previously incorrectly fail with the message:
```
Cannot query field "primaryFunction" on type "Human"
```
=> Fix incorrect rejection of queries with nested fragments.

src/cli.js
Should address #78 
Different shells can expand globs differently and it might not necessarily match up. Because the input path list order determines the output order, it makes sense to sort these so that codegen'd
types don't keep changing between commits of developers on different terminals.
=> Sort input paths after glob expansion.

src/swift/language.js, test/swift/__snapshots__/codeGeneration.js.snap, test/swift/__snapshots__/language.js.snap, test/swift/language.js
Should address #88 
Split the description by new lines, and print each line of the description as a comment
=> Handle multiline descriptions in swift

src/swift/language.js, test/swift/language.js
Otherwise, apollo-codegen results in errors where multiline comments are not wrapped correctly.
=> Split on \n as newline character in swift codegen

src/typescript/types.js
At the moment, apollo-codegen outputs the type `String` as a fallback for custom scalar types (the JS `String` type, very different from TS `string`).
After this patch, it correctly outputs `string`.
If you take a quick look at the patch, I'm fairly certain this was simply unintended behaviour (and lucky that it worked at all), caused by an implicit `toString` on a value of the wrong type.
=> TS: Output `string` not `String` for fallback scalar type.

src/swift/codeGeneration.js, test/swift/__snapshots__/codeGeneration.js.snap
This adds namespacing to the generated `JSONDecodable`and `JSONEncodable` in Swift.
Consumers of the generated code can have identical symbol names, so the generated code should include the package name in the protocol reference.
=> Add namespacing to JSONDecodable & JSONEncodable extensions in Swift

src/typescript/codeGeneration.js, test/typescript/__snapshots__/codeGeneration.js.snap
This makes tslint configurations which use the "require-header" rule not complain about the generated file.
Would be nice with an option to add a header from CLI.
=> Emit /* tslint:disable */ prior to comment

src/errors.js
This information exists but isn't exposed in the error messaging. When run on a big project from
CLI -- without the filenames, it's difficult to track down where the errors are being triggered from. Solves #82 
I don't know what the ideal format here is, but I truncated the filename to be the last 4 parts of the file since this worked out well for my use case. There's definitely room for iteration here.
Regarding line numbers -- these weren't correct when coming from javascript source files, but are correct coming from `.graphql` files. I've left the line numbers out for now, since the filename is already a huge improvement -- once you know that it is less difficult to find the source of the validation error once you know the filename.
=> Add filename to error messages printed from CLI

src/flow/codeGeneration.js, src/typescript/codeGeneration.js
In typescript/codeGeneration.js:
fragmentSpreads and inlineFragments may be null.
This is the case for a query with a simple return type that does not return an object.
Example Query:
```
query basicQuery {
hello: world
}
```
Example schema:
```
type Query {
world: String
}
```
I ran into this case when querying for a `currentUserLoginEmail` that returns a string type:
```
query currentUser {
currentUser {
id
contact: contactByContactId {
id
firstName
lastName
}
}
loginEmail: currentUserLoginEmail
}
```
=> fix(typescript) null check fragmentSpreads and inlineFragments

src/flow/codeGeneration.js, src/flow/language.js, src/typescript/codeGeneration.js, src/typescript/language.js, test/flow/__snapshots__/codeGeneration.js.snap, test/flow/codeGeneration.js, test/misc/schema.graphql, test/misc/schema.json, test/typescript/__snapshots__/codeGeneration.js.snap, test/typescript/codeGeneration.js
fixes #117
This fix was made to the Swift target previously but was not made for Flow/Typescript targets.
Tests were also added to ensure the simplest case works.
=> Support multiline comments for Flow/Typescript targets

package.json, src/cli.js, src/compilation.js, src/generate.ts, src/swift/codeGeneration.js, test/swift/__snapshots__/codeGeneration.js.snap, test/swift/codeGeneration.js
This introduces - to Swift only - the notion of `operationId`s, which are unique identifiers for operations. The primary use for these ids is registration with a server, to do query persistence and whitelisting.
The operation id is generated by concatenating the formatting-normalized source of the operation with the formatting-normalized sorted sources of the fragments it references. It's a whitespace-agnostic "fingerprint" of the operation source that's sent to the server. Note, however, that it is *not* agnostic to field order.
When the `operation-ids-path` option is provided to `apollo-codegen`, the following occurs:
* An `operationId` static property is added to the operation class definition.
* The operation id and concatenated operation/fragment source blob are added to a map file. …
=> Generate Swift operation IDs and operation <--> operation ID mapping file

src/flow/codeGeneration.js, src/flow/language.js, src/flow/types.js, src/typescript/codeGeneration.js, src/typescript/language.js, test/flow/__snapshots__/codeGeneration.js.snap
Removes some unused variables (`inInterface`, `forceNullable`) and adds an explicit `isNullable` property which is passed down to all property declarations, as well as an `isInput` property which is used to mark that the property should be optional in the type definition if it's nullable, as pointed out in #134. Will open a similar PR in TS to address #81.
=> Optional Flow Inputs

src/typescript/codeGeneration.js
These changes were supposed to get in #156 when migrating over
from Flow it looks like, but they aren't there.
=> Fix missed toggling of input types in typescript target

.travis.yml, package.json
I had the same lodash problem that was fixed in https://github.com/apollographql/apollo-codegen/pull/165 by @kompfner. It looks like the cli would have tested fine as the lodash dependency was still being pulled in by jest.
This PR adds a simple smoke test to make sure that the cli still starts up even when jest isnt around.
=> add smoke test to ci

.npmignore
Mentioned in #164.
Published versions of apollo-codegen should not publish with tests -- this leads to confusion sometimes when node_modules is indexed/accessed by some other tool.
=> Add test/ to .npmignore

src/cli.js, src/downloadSchema.js
The method was previously hard-coded as `POST`, this PR allows the user to specify the request method as either `GET` or `POST`.
=> Pass in HTTP Request Method for introspect-schema

src/swift/codeGeneration.js, test/swift/__snapshots__/codeGeneration.js.snap
Line breaks in enum descriptions were not being preserved as multi-line comments.
I chose to move the comment above the enum case rather than replacing newlines with spaces to keep it all on one line.
=> Fix multi-line enum comments

src/cli.js
Looks like I'm a big javascript noob, but looks like I needed to include a boolean type flag to make "merge-in-fields-from-fragment-spreads" read a boolean.
I don't see any tests for the CLI, and I'm not sure how to test this locally. @martijnwalraven any advice so I can make sure I did it right this time?
=> Set merge-in-fields-from-fragment-spreads as boolean type

package.json, src/compilation.js
I'm not familiar with `sjcl` but it seemed silly to introduce a
new dependency when node includes sha256 hashing in the standard libs.
=> `Replace `sjcl` with standard `crypto` module

src/swift/codeGeneration.ts, src/swift/language.ts
Swift only.  Apologies the issue was added to the appollo-ios repo.  If need be, I can create a ticket here, but I do feel it's reasonable as it's Swift specific.  Certainly open to any feedback on this. Cheers
Inserts deprecation code under code comment for properties if there's deprecation. 
uses: `__Field.isDeprecated` & `__Field.deprecationReason`
```
/// The categorization of this pie.
@available(*, deprecated, message: "Obsolete and will eventually be removed. Use the hierarchical `categorization` field instead.")
public var category: PieCategoryEnumType {
get {
return snapshot["category"]! as! PieCategoryEnumType
}
set {
snapshot.updateValue(newValue, forKey: "category")
}
}
```
Inserts deprecation code above the enum case if there's deprecation.
uses: `__EnumValue.isDeprecated` & …
=> close apollographql/apollo-ios#124 Add in deprecations for swift

src/loading.ts
The following tagged template literal `q1` and `q2` are valid syntax in JS and TS, however apollo-codegen extracts GraphQL query from not `q1` but only `q2`.
```ts
const q1 = gql    `query MyQuery { ... }`; // Not extracted
const q2 = gql`query MyQuery { ... }`;   // Extracted 
```
=> Allow spaces between tag name and backquote

README.md, src/cli.js, src/generate.ts, src/scala/codeGeneration.js, src/scala/index.js, src/scala/language.js, src/scala/naming.js, src/scala/types.js, src/scala/values.js, test/scala/__snapshots__/codeGeneration.js.snap, test/scala/__snapshots__/language.js.snap, test/scala/codeGeneration.js, test/scala/language.js, test/scala/types.js
Adds a new target to `apollo-codegen` that emits Scala types for queries through `case class` model types and companion objects that provide type conversions.
=> Initial support for Scala.js with working queries and mutations

README.md
Just passing by… I found minor mistake in the example.
=> Corrected example `__typename` usage in Readme.md

src/typescript/codeGeneration.js, src/typescript/types.js
This is fix for https://github.com/apollographql/apollo-codegen/issues/223
=> --passthroughCustomScalars option was not handled in Typescript generator

src/flow/codeGeneration.js, test/fixtures/misc/schema.graphql, test/fixtures/misc/schema.json, test/flow/__snapshots__/codeGeneration.js.snap, test/flow/codeGeneration.js
Now it works. There was an exception when `rootField.fields` was `undefined`
=> Flow code generation for scalar fields in document root

src/flow/codeGeneration.js, src/typescript/codeGeneration.ts, test/fixtures/misc/schema.graphql, test/fixtures/misc/schema.json, test/flow/__snapshots__/codeGeneration.js.snap, test/flow/codeGeneration.js, test/typescript/__snapshots__/codeGeneration.js.snap, test/typescript/codeGeneration.js
Before, multiline comments were printed correctly only in record types.
=> Allow multiline comments in enums

package.json, test/test-utils/preprocessor.js
Was running into problems finding the right source when errors / logs are reported within tests so I decided to try fixing sourcemaps. Seems like using ts-jest instead of our custom preprocessor fixes it
=> Update Jest Typescript support to use ts-jest

src/swift/codeGeneration.ts, test/swift/__snapshots__/codeGeneration.ts.snap
Conforming to Apollo.JSONDecodable/Encodable by `extension` on enum types does not compile when wrapping the generated output in a namespace (`--namespace <Namespace>` CLI flag), since Swift does not allow extensions from within a nested scope.
Before this patch, generated output (with namespace) would look like this:
```swift
public enum WhateverNamespace {
public enum CaseCategory: String {
// …
}
extension CaseCategory: Apollo.JSONDecodable, Apollo.JSONEncodable {}
// ^ Compiler error: Declaration is only valid at file scope
}
```
After this patch, it'll be something more along these lines:
```swift
public enum WhateverNamespace {
public enum CaseCategory: String, Apollo.JSONDecodable, Apollo.JSONEncodable {
// …
}
}
```
=> [Swift] Fix output not compiling when using --namespace with enums

src/typescript/codeGeneration.ts, test/typescript/__snapshots__/codeGeneration.js.snap, test/typescript/codeGeneration.js
Previously `__typename: string` was generated for cases like `DroidWithName` in the tests.
=> Correct typename values for fragments on non-abstract types

src/flow/codeGeneration.js, test/flow/__snapshots__/codeGeneration.js.snap, test/flow/codeGeneration.js
I noticed that I sometimes got `__typename: "undefined"` when generating Flow code. It didn't seem to happen in TypeScript. I compared the TypeScript and Flow implementations and copied some things over from TypeScript and managed to fix the bug!
Schema:
```graphql
schema {
query: Query
}
type Query {
persons: [Person]
}
type Person {
name: String
}
```
Query:
```graphql
query Test {
persons {
name
}
}
```
Generated Flow code, before:
```js
export type TestQuery = {|
persons: ? Array<? {|
__typename: "undefined", // NOTE THE "undefined"!
name: ?string,
|} >,
|};
```
Generated Flow code, after:
```js
export type TestQuery = {|
persons: ? Array<? {|
__typename: "Person", // Yay!
name: ?string,
|} >,
|};
```
=> Fix __typename for List types in Flow

src/flow/codeGeneration.js
when generating Typescript, `tslint:disable` is added to the top of the generated file. ESLint should be disabled for Flow in the same way.
=> disable ESLint when generating Flow types

src/swift/codeGeneration.ts, src/swift/helpers.ts, test/swift/__snapshots__/codeGeneration.ts.snap
This PR addresses the issue presented in #284.  
* Update generated enums to implement `RawRepresentable` protocol directly so that we can wrap the unknown value received from the server and echo it back on encoding.  This allows clients to use the `.unknown` enum case and actually use the value they received from the server if they choose to do so.
* Implement `Equatable` protocol on Enum to allow for `XCTAssertEqual` to work properly.
=> Swift Support Unknown Enums

src/flow/codeGeneration.js, test/flow/__snapshots__/codeGeneration.js.snap, test/flow/codeGeneration.js
This PR just ports https://github.com/apollographql/apollo-codegen/pull/251 from Typescript to Flow.
=> Flow: Correct typename values for fragments on non-abstract types

src/swift/language.ts, test/swift/language.ts
This isn't ready to merge, but I wanted to run it by you for a second set of eyes. The issue is that if I have a SelectionSet that asks for a field named `type` it generates a Swift struct with,
```swift
public struct Type: GraphQLSelectionSet
```
But `Type` there is a reserved word and needs to be escaped. This change runs all structs through the escaping function so the above issue doesn't happen any more.
=> Escaping struct names

src/flow/codeGeneration.js, src/typescript/codeGeneration.ts, test/flow/__snapshots__/codeGeneration.js.snap, test/flow/codeGeneration.js, test/typescript/__snapshots__/codeGeneration.js.snap, test/typescript/codeGeneration.js
Fix the issue that nested property objects has `__typename: string`.
Before:
```js
{
__typename: "Human",
friendsConnection: {|
___typename: string,
edges: ? Array<? {|
__typename: string,
node: ?( {
__typename: "Human",
name: string,
} | {
__typename: "Droid",
name: string,
}
),
|} >,
|},
starships: ? Array<? {|
__typename: string,
name: string,
|} >,
}
```
After:
```js
{
__typename: "Human",
friendsConnection: {|
__typename: "FriendsConnection",
edges: ? Array<? {|
__typename: "FriendsEdge",
node: ?( {
__typename: "Human",
name: string,
} | {
__typename: "Droid",
name: string,
}
),
|} >,
|},
starships: ? Array<? {|
__typename: "Starship",
name: string,
|} >,
}
```
=>  Add typeName for nested property objects

src/javascript/flow/__tests__/__snapshots__/codeGeneration.ts.snap, src/javascript/flow/__tests__/codeGeneration.ts, src/javascript/flow/language.ts, src/javascript/flow/printer.ts
Fixes #306
Just print everything on the same line for now to unbreak output.
Modifications to make the output prettier will come later
=> Flow: handle multiline comments in GraphQL schema

src/typescript/language.ts, test/typescript/__snapshots__/codeGeneration.js.snap
When using typescript, it is often more powerful/easier to use an `interface` as you can destructure it for reuse.  The easiest example is taking query data that is passed to react widgets, where you want those react widgets to remains strongly typed.  As a ts `type`, you cannot `Pick` from it, whereas an interface, you can `Pick<MyQuery, 'user'>` as a widget type or simply use `MyQuery['user']` to access the type inside the interface.
=> Use typescript interfaces where possible

.travis.yml, src/javascript/typescript/printer.ts
Take advantage of package-lock for tests. Otherwise we'd be installing different versions of things :(
=> Use npm@5 for all versions of node in TravisCI

package-lock.json, package.json, src/javascript/types/augment-babel-types.ts
New @types/babel-types includes type definitions for the typescript nodes.
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/21972
This means we don't have to hack around this anymore and we can update our TS target to use the new ts nodes throughout the TS target code generation.
=> update @types/babel-types to 7.0.0 with new ts types

src/javascript/typescript/__tests__/__snapshots__/codeGeneration.ts.snap, src/javascript/typescript/__tests__/codeGeneration.ts, src/javascript/typescript/__tests__/helpers.ts, src/javascript/typescript/codeGeneration.ts, src/javascript/typescript/helpers.ts, src/javascript/typescript/language.ts, src/javascript/typescript/printer.ts
This updates the typescript modern generator to use TS nodes from the `@babel/types` library. This fixes some invalid output in the TS generated files since we were really using flow nodes, which have slight syntax differences.
=> Generate using TS node types in Typescript Modern

src/javascript/flow/__tests__/__snapshots__/codeGeneration.ts.snap, src/javascript/flow/codeGeneration.ts, src/javascript/typescript/__tests__/__snapshots__/codeGeneration.ts.snap, src/javascript/typescript/codeGeneration.ts
This PR adds the generation of the variables object type for each operation. In the case of flow it generates a flow annotation, and in the case of Typescript, an interface. It follows the same nullability rules as when creating input objects (they can be set to undefined or not even set).
=> *-Modern variables

src/javascript/flow/__tests__/__snapshots__/codeGeneration.ts.snap, src/javascript/flow/codeGeneration.ts, src/javascript/flow/helpers.ts, src/javascript/flow/language.ts, src/javascript/types/augment-babel-types.ts
Fixes #325 (_Flow Modern flattens Arrays in output_)
This is an alternative implementation versus #342 which:
* Provides full support of arbitrary nullable/nested lists without special casing top-level lists/nulls. (The `typeAnnotationFromGraphQLType` function now recursively covers all cases; the type annotations for field properties are now correctly generated from this same logic as well).
* Does not include the inferred inflection change discussed in that PR, which is unrelated to the array-flattening issue
=> Fix Flow-Modern incorrectly-flattened array generation

src/cli.js
Header values are currently corrupted if they contain semicolons (introspect-schema and download-schema commands). As of https://tools.ietf.org/html/rfc7230 semicolons in header values are allowed.
=> Support semicolons in header values

src/generate.ts
When you run `npm run compile` it fails with error:
```
src/generate.ts(140,31): error TS2339: Property 'operationId' does not exist on type '{}'.
src/generate.ts(141,23): error TS2339: Property 'operationName' does not exist on type '{}'.
src/generate.ts(142,25): error TS2339: Property 'sourceWithFragments' does not exist on type '{}'.
```
This happens because `Object.values` is loosing types, so I've changed it to `Object.keys(o).map(k => o[k])`.
=> Fix "'operationId' does not exist on type '{}'" on compile

src/errors.ts
Replace all occurrences of console.log by console.error in logError functions.
This allows using apollo-codegen with other commands in a script, and separating errors from normal output.
A work-around would be to use shell redirections.
I have not written any test in the PR.
=> Log errors to stderr instead of stdout

package-lock.json, package.json, src/printSchema.ts
I noticed that `graphql` exposes [some options](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/graphql/utilities/schemaPrinter.d.ts#L8) in `printSchema` function.
I need it in order for some other plugin/parser to be able to digest schema definition.
So here are two changes:
- update `@types/graphql` (these options is a recent changes)
- allow passing options to `apollo-codegen`'s `printSchema`
=> Add printSchema options

package-lock.json, package.json, test/compiler/visitors/typeCase.ts
Need to update graphql version for solving syntax changed on inherited interfaces https://github.com/graphql/graphql-js/pull/1169 
Separate multiple inherited interfaces used `,` previously but have been changed by `&`
=> Update graphql version from 0.12.3 to 0.13.1

src/swift/codeGeneration.ts, test/swift/__snapshots__/codeGeneration.ts.snap
This PR fixed the error when using snake-case in property name when generating the code for swift.
The code is using the wrong key.
=> Fix swift codegen key when using snake-case property

README.md
> If you're using a client like apollo-client that **does** this automatically for your GraphQL operations
Is **does** the correct word here, as opposed to **doesn't**?
=> Typo on command name

src/typescript/codeGeneration.ts, src/typescript/language.ts, test/typescript/__snapshots__/codeGeneration.js.snap
Many IDEs that work with TypeScript will use JSDoc comments on types, fields, and enum variants in hover and completion contexts. Changing the generated code to wrap the `description` property in a JSDoc comment instead of a regular comment or postfix comment makes those IDEs surface the GraphQL description to the developer as they're working.
Fixes #384
=> Emit JSDoc comments for TypeScript types and enums

src/javascript/typescript/__tests__/__snapshots__/codeGeneration.ts.snap, src/javascript/typescript/language.ts
In `ts-modern` the generated input types are not exported and thus not usable from outside the generated module. (Similiar issue in Flow was #320 ). 
This PR adds the missing 'export's to the types.
*Example **before**:*
```
//==============================================================
// START Enums and Input Objects
// All enums and input objects are included in every output file
// for now, but this will be changed soon.
// TODO: Link to issue to fix this.
//==============================================================
// ===> SearchFilter is an input type and not exported:
interface SearchFilter {
searchString?: string | null;
maxHits?: number | null;
}
```
*Example **after**:*
```
//==============================================================
// START Enums and Input Objects
// …
```
=> [ts-modern] export generated input types

src/javascript/flow/__tests__/__snapshots__/codeGeneration.ts.snap, src/javascript/flow/language.ts
/label bug
/label flow
This fixes #421 by ensuring that all `InputObject` annotations are `$Exact` when using the `flow-modern` generator.
EDIT: I accidentally included the "typescript" label, and I don't see a way to remove it. If someone could remove that for me, it would be appreciated!
=> fix #421 - generate $Exact InputObject annotations

src/cli.js, src/javascript/flow/__tests__/helpers.ts, src/javascript/flow/helpers.ts, src/javascript/typescript/__tests__/helpers.ts, src/javascript/typescript/helpers.ts
/label bug
/label flow
/label typescript
This fixes inconsistent treatment of the `passthrough-custom-scalars` option, and adds the ability to use `custom-scalars-prefix` on `flow-modern` and `typescript-modern`.
The `-modern` generators had the opposite behavior as the rest of the generators, although they correctly followed the guidance of the `passthrough-custom-scalars` CLI description. To minimize breakage, I changed these and the description to match the behavior of the other generators.
This fixes #418.
=> fix inconsistent treatment of passthrough-custom-scalars

README.md, packages/apollo-codegen-flow/src/__tests__/__snapshots__/codeGeneration.ts.snap, packages/apollo-codegen-flow/src/codeGeneration.ts, packages/apollo-codegen-typescript/src/__tests__/__snapshots__/codeGeneration.ts.snap, packages/apollo-codegen-typescript/src/codeGeneration.ts, packages/apollo-codegen/src/cli.js, packages/apollo-codegen/src/cli.ts, packages/apollo-codegen/src/generate.ts
Previously, modern targets outputted types right next to the GraphQL queries, which didn't handle many use cases. This makes it possible to specify an output file or directory and have the CLI write the types there.
One special change to handle outputting to both a single and multiple files is the introduction of a `common` body of code, which is included in every file but not duplicated when merging everything into one file.
=> Restore ability to specify output path for modern targets

packages/apollo-codegen/src/cli.ts
This typo breaks backwards compatibility with `flow` users from `0.19.0` because we can no longer use `flow-legacy` since you can't provide the right CLI argument and the switch statement looks for the correct argument (`flow-legacy`) instead of the only one you can put on the CLI (`flow-leagcy`)
=> [cli, flow-legacy] Fix CLI typo for flow-legacy

packages/apollo-codegen-flow/src/__tests__/__snapshots__/codeGeneration.ts.snap, packages/apollo-codegen-flow/src/codeGeneration.ts
Currently when the output to `apollo codegen:generate` is not specified and the target is flow, all of the generated files have a .ts extension, but it should be .js.
=> Change generated flow files extension to .js instead of .ts

packages/apollo-cli/README.md, packages/apollo-cli/src/commands/schema/download.ts
Hopefully less pain moving from apollo-codegen.
=> added clarity to schema:download

packages/apollo-cli/README.md, packages/apollo-cli/package.json, packages/apollo-cli/src/commands/codegen/__tests__/__snapshots__/generate.test.ts.snap, packages/apollo-cli/src/commands/codegen/__tests__/generate.test.ts, packages/apollo-cli/src/commands/codegen/generate.ts, packages/apollo-cli/src/generate.ts
Fixes #469. Before the change from `apollo-codegen` to `apollo` cli, flow type definitions were output into a `__generated__` directory, next to their respective source files.
This adds a `localDirectory` flag that accepts a name to use locally for generated types. For example:
```sh
apollo generate:flow **/*.graphql --localDirectory=__generated__
```
This flag is ignored if `--output` is specified.
=> Restore ability to put generated files in a directory relative to source

packages/apollo-cli/src/commands/codegen/generate.ts, packages/apollo-cli/src/commands/queries/check.ts, packages/apollo-cli/src/commands/schema/check.ts, packages/apollo-cli/src/commands/schema/publish.ts, packages/apollo-cli/src/engine-cli.ts, packages/apollo-cli/src/fetch-schema.ts, packages/apollo-cli/src/generate.ts, packages/apollo-cli/src/git.ts, packages/apollo-cli/src/printer/ast.ts, packages/apollo-cli/src/printer/diff.ts, packages/apollo-cli/src/printer/print.tsx, packages/apollo-cli/tsconfig.json
=> Remove unused locals in Apollo CLI

.vscode/launch.json, packages/apollo-cli/src/validation.ts, packages/apollo-language-server/src/diagnostics.ts
=> Share validation logic between CLI and language server

packages/apollo-cli/README.md
=> Add docs for Apollo config

packages/apollo-cli/src/commands/schema/__tests__/check.test.ts, packages/apollo-cli/src/commands/schema/__tests__/publish.test.ts, packages/apollo-cli/src/commands/schema/check.ts, packages/apollo-cli/src/commands/schema/download.ts, packages/apollo-cli/src/commands/schema/publish.ts, packages/apollo-cli/src/config.ts, packages/apollo-cli/src/fetch-schema.ts, packages/apollo-cli/src/load-schema.ts, packages/apollo-language-server/src/languageProvider.ts, packages/apollo-language-server/src/project.ts, packages/apollo-language-server/src/workspace.ts, packages/apollo-vscode/package-lock.json, packages/apollo-vscode/src/extension.ts
=> Support jumping to definitions in schema

packages/apollo-language-server/src/languageProvider.ts, packages/apollo-language-server/src/project.ts, packages/apollo-vscode/syntaxes/graphql.json
=> Fix missing descriptions and add more hover information for arguments

package-lock.json, packages/apollo-language-server/package.json, packages/apollo-language-server/src/document.ts, packages/apollo-language-server/src/languageProvider.ts, packages/apollo-language-server/src/project.ts, packages/apollo-language-server/src/typings/graphql-language-service.d.ts
=> Code complete default query variables

packages/apollo-cli/src/load-config.ts
* Check if a custom config for queries hasn't been setup, else fallback to flags.queries
=> Stop default flag values from overriding custom config

packages/apollo-codegen-typescript/src/language.ts
Only output comment for input if there is one, this is aligned with how enums are generated: https://github.com/apollographql/apollo-cli/blob/master/packages/apollo-codegen-typescript/src/language.ts#L57-L62
=> [typescript] Only output comment for input if there is one

packages/apollo-cli/src/commands/codegen/generate.ts, packages/apollo-cli/src/commands/schema/check.ts, packages/apollo-cli/src/commands/schema/download.ts, packages/apollo-cli/src/config.ts, packages/apollo-cli/src/load-config.ts, packages/apollo-codegen-core/src/loading.ts
=> Scan all files for queries and reduce use of manual endpoints

packages/apollo-cli/src/load-schema.ts
Helps in situations where one method fails like when an endpoint exists but introspection is disabled.
=> Fall back to other methods of schema loading when one fails

packages/apollo-codegen-typescript/src/__tests__/__snapshots__/codeGeneration.ts.snap, packages/apollo-codegen-typescript/src/codeGeneration.ts
=> [TS] Sort global types so order is not determined by order of appearance

packages/apollo-cli/src/commands/codegen/generate.ts
Currently it's not possible to use the `--watch` options if the stdin is not a tty (e. g. if the command is run using the [concurrently](https://www.npmjs.com/package/concurrently) cli tool). You can reproduce this bug with the following command:
```bash
apollo codegen:generate --target=typescript --schema=src/data/schema.json '--queries=src/**/*.tsx' --watch < /dev/null
```
You'll see the following output:
```
✔ Loading Apollo config
✔ Scanning for GraphQL queries (6 found)
✔ Generating query files with 'typescript' target - wrote 3 files
Press any key to stop.
TypeError: process.stdin.setRawMode is not a function
at waitForKey (~/Projects/omnicalc/node_modules/apollo/lib/commands/codegen/generate.js:17:19)
at Generate.run (~/Projects/omnicalc/node_modules/apollo/lib/commands/codegen/gene …
```
=> Allow to run `apollo codegen:generate --watch` on non tty devices

packages/apollo-codegen-typescript/src/__tests__/__snapshots__/codeGeneration.ts.snap, packages/apollo-codegen-typescript/src/codeGeneration.ts
=> Prepend ./ to TS relative paths to make them valid, fix #543

packages/apollo-cli/src/commands/schema/download.ts, packages/apollo-cli/src/config.ts, packages/apollo-cli/src/fetch-schema.ts, packages/apollo-cli/src/load-config.ts, packages/apollo-cli/src/load-schema.ts
Often developers use a self-signed certificate for local services. In development process is not uncommon to see those kind of https requests without a Root CA signed certificate. This PR tries to solve the issue reported on #199 when using `apollo-cli` for downloading the GraphQL schema.
`schema:download` has a new option `--insecure` or equally `-k`  for skipping certificate validation. These names were chosen following the popular unix command `curl` convention.
It is my first PR on the project so any kind of feedback is more than welcome.
Fixes #199
=> Support for self-signed certificates

packages/apollo-language-server/copy-apollo-libs.sh, packages/apollo-language-server/src/server.ts, packages/apollo-vscode-webview/webpack.config.js
Two main fixes:
1. Copy the entire monorepo package folders into the server `node_modules` so that `*/lib/*` resolves to the files there.
2. Add an extra rule to handle `.mjs` files to prevent Webpack issues with `graphql-js`
=> Fix the VSCode extension build setup

package.json, packages/apollo-language-server/src/project.ts, packages/apollo-vscode/package.json
This PR cuts the stats query over to Druid. Also add watch support for better extension development.
=> Migrate stats query to druid, update how the data is consumed

packages/apollo/src/commands/queries/register.ts, packages/apollo/src/operations/registerOperations.ts
@abernix this adds client identity to the registration step!
=> Require client identity for registering operations

packages/apollo/src/commands/queries/check.ts, packages/apollo/src/commands/queries/extract.ts, packages/apollo/src/helpers/commands/queries/commonTasks.ts
**Breaking changes:** This changes the output format of the manifest generated by `queries:extract` to be in a more evolvable format.  Existing users of the manifest produced by `manifest.json` should take care to observe the new manifest format, as indicated by the top-level presence of a `version` attribute (now `1`, previously `undefined`).
In general, this just moves some bits of often repeated portions of the CLI into a unified location where they can be shared by more modules as we use more and more portions in multiple places.
=> Restructure `apollo queries:extract` logic and manifest format.

packages/apollo-codegen-core/src/utilities/__tests__/graphql.test.ts, packages/apollo-codegen-core/src/utilities/graphql.ts, packages/apollo/src/commands/queries/extract.ts, packages/apollo/src/commands/schema/check.ts, packages/apollo/src/commands/schema/download.ts, packages/apollo/src/commands/schema/publish.ts, packages/apollo/src/config.ts, packages/apollo/src/fetch-schema.ts, packages/apollo/src/helpers/commands/queries/commonTasks.ts, packages/apollo/src/load-schema.ts
~**Note:** This PR depends on #611 and #613 and merges into #611.  If #611 lands first, this should be re-targeted to land in `master`.~
---
The commits in this PR avoid re-running the introspection result from a GraphQL server as a client schema when not necessary.  This is particularly important to maintain an introspection result which is consistent with the version of `graphql` which is used on the actual GraphQL server being introspected.  Previously, this was re-running that introspection in the Apollo CLI’s `graphql` executor which produced a different result since there is no guarantee that the server is using `graphql@0.13.2`, the version currently used by the `apollo` CLI.
Additionally, thanks to @jbaxleyiii’s work in 88a248c, operations in the manifest now properly consider …
=> Avoid re-introspecting within local `graphql` context and exclude client-only directives.

package-lock.json, packages/apollo-language-server/package.json, packages/apollo-language-server/src/__tests__/diagnostics.ts, packages/apollo-language-server/src/diagnostics.ts, packages/apollo-language-server/src/project.ts
When building up an array of diagnostics in the language server, we should handle type definitions separately.
This PR narrows the scope of the `collectDiagnostics` function to be responsible for operations only.
This PR does not implement diagnostics for type defs, this just removes a false positive.
Still trying to figure out the best way to a good `watch` flow while working on the extension. Updated some of the scripts/dev config in the language server and extension packages. This simplifies it a bit - all that is required now is a symlink from `apollo-language-server/lib` to `apollo-vscode/server`. Still a WIP, but it feels like a step in the right direction. I'm _very_ open to feedback here.
Before:
After:
=> Filter type definitions

package-lock.json, package.json, packages/apollo-language-server/package.json, packages/apollo-language-server/src/loadingHandler.ts, packages/apollo-language-server/src/project.ts, packages/apollo-language-server/src/server.ts, packages/apollo-language-server/src/workspace.ts, packages/apollo-vscode/package-lock.json, packages/apollo-vscode/package.json, packages/apollo-vscode/src/extension.ts, packages/apollo-vscode/src/statusBar.ts, packages/apollo/README.md, packages/apollo/package.json, packages/apollo/src/commands/schema/download.ts, packages/apollo/src/commands/schema/publish.ts, packages/apollo/src/config.ts, packages/apollo/src/fetch-schema.ts, packages/apollo/src/load-schema.ts
This PR:
* adds functionality to the VSCode extension for switching to / developing against different schema tags.
* adds the ability to publish a schema to engine with a tag via the CLI and the `--tag` flag.
For context:
Schemas can be "branched" in a similar way that one might make a branch in a git repo. This concept allows developers to publish different "branches" (tags) of a schema to engine. Publishing a new tag to engine makes the new introspection available to a client, in this case, VSCode.
The result here is that an extension user can switch tags on the fly and expect all the benefits that an introspection provides: autocomplete, syntax errors, and other relevant information _specific to that tag_.
=> VSCode: Schema tag switching

packages/apollo/src/load-schema.ts
This reverts commit b48e7bf31ebb9f5cb8f4daa7830a8fb8c4c81d45.
As corroborated by the trending number of 👍 emotes on #560, this PR introduced a number of `try` `catch`es which silenced relatively useful information from their _tried_ operations.  I'm happy to help figure out a better approach but since this seems to have caused many more problems than it solved, we should consider a different approach.
cc @shadaj 
Closes #560
=> Revert "Fall back to other methods of schema loading... (#533)

packages/apollo-language-server/package.json
Should prevent this error:
```
Error: Cannot find module 'dotenv'
at Object.exports.loadConfig (~/Projects/test-vue-cli-apollo/node_modules/apollo-language-server/lib/config.js:141:21)
```
=> fix: add missin dotenv dep

packages/apollo/README.md
The original example didn't work with the language server because the server looks under the `service` key for endpoint configuration. This updates the example to a config that will work for local endpoints.
=> Fix local endpoint config example to use the service key instead of endpoint

.circleci/config.yml, apollo.config.js
This PR re-enables operation validation against the pushed engine service
=> turn back on operation checks

packages/apollo/src/commands/client/codegen.ts
Currently whenever `client:codegen` is used the command outputs the following:
```
✔ Generating query files with 'typescript' target - wrote undefined files
```
`undefined` is because `writtenFiles` is `undefined`. `writtenFiles` is `undefined` because `write` doesn't return any value. `generate` returns the number of written files, so that should be returned in `write` as well.
=> Make sure writtenFiles is propagates

packages/apollo-language-server/src/__tests__/diagnostics.ts, packages/apollo-language-server/src/utilities/source.ts
This fixes the case where error markers are placed incorrectly when an error refers to a range in the first line of inlined GraphQL.
Previously error locations (and thus editor decorations) would disregard the column offset. Error were reported like this:
```
foo = gql`query Foo { bar }`
^^^
```
This change makes the location add the column offset it referring to the first line:
```
foo = gql`query Foo { bar }`
^^^
```
=> Small bug fix: Correctly incorporate column offset in decorations

packages/apollo-language-server/src/document.ts, packages/apollo-language-server/src/project/base.ts
Python does not have tagged templates but it's safe to assume that the user will use a function named `gql()` to wrap document literals in code.
There is currently no GitHub issue tracking this feature, it was however discussed on the Apollo Slack.
=> New Feature: Add Python document extractor to the language server

packages/vscode-apollo/package.json, packages/vscode-apollo/src/extension.ts, packages/vscode-apollo/syntaxes/graphql.py.json
This depends on the language server supporting Python (PR #693) for IntelliSense.
Apollo config defaults to JS/TS files only, so it's required to add `*.py` to `apollo.config.js` under `client.includes` before completion/validation starts to work.
Here's everything in action:
=> New Feature: Add Python support to the editor plugin

packages/apollo/src/commands/client/check.ts, packages/apollo/src/commands/service/check.ts
*:check currently calls this.exit() on success cases. This should only be called if there are failures, else
the script throws an error.
=> Prevent unnecessary failures in *:check

packages/apollo-codegen-core/src/loading.ts
When [GraphQL](https://github.com/graphql/graphql-js/blob/master/src/language/parser.js#L124) `parse` fails to parse file(s) errors are silently ignored.
Was having an issue with a whitespace character in one of our `.graphql` files which was rather difficult to trace. This character is added as a result of saving the file in XCode, so it'd be a common use case.
**Example:**
```
Warning: error parsing GraphQL file "Queries/Enrollments.graphql"
Syntax Error: Cannot contain the invalid character "\u0010".
Queries/Enrollments.graphql (6:1)
5: }
6: 
^
7: 
at syntaxError (/../code/apollo-cli/node_modules/graphql/error/syntaxError.js:24:10)
at readToken (/../code/apollo-cli/node_modules/graphql/language/lexer.js:174:34)
at Object.lookahead …
```
=> Warn on GraphQL parser exceptions

packages/apollo-language-server/src/config.ts, packages/apollo-language-server/src/workspace.ts, packages/apollo/src/Command.ts
Cosmiconfig needs to know it can look elsewhere when a custom config is specified. This allows the --config to be something other than apollo.config.js.
Note: if a custom config is specified, it will take precedence over our defaults.
Fixes #683
=> Allow custom configs

packages/apollo-language-server/src/engine/index.ts
Throw errors we receive from Engine so we can provide the right feedback to users and handle the errors.
Tested for `client:check` and `client:push` using invalid operations against a published schema.
=> Don't swallow errors from Engine

packages/apollo/src/commands/client/codegen.ts
Only throw an error if we have neither operations _or_ fragments.
Tested this on a demo project with fragments only to confirm the fix.
Fixes #684
=> Allow fragments only for codegen

packages/apollo/src/Command.ts, packages/apollo/src/commands/client/codegen.ts, packages/apollo/src/commands/client/extract.ts, packages/apollo/src/commands/service/push.ts
Pushing from a local schema was previously supported through the CLI via the --endpoint flag. We could continue to support that through some logic where we parse that flag but instead I've chosen to add a new flag that's more semantic and less magic.
This PR also allows `client:codegen` to point to a local schema from the CLI with the same flag.
* Tested and successfully published with a local .gql schema using the --localSchemaFile flag.
* Tested and successfully generated typescript types with a local .gql schema using the same flag.
Fixes #672
=> Support localSchemaFile flag to push to a service from local schema

packages/apollo/src/Command.ts, packages/apollo/src/commands/client/codegen.ts
After the overhaul, support for the queries flag in codegen was altered. This restores previous behavior and add includes and excludes flags.
Note: excludes patterns don't work in watch mode due to a limitation with
Gaze, the file watcher we're using.
Tested:
* Using flags in combinations: `includes`, `includes + excludes`, `queries`
* With `watch` flag
=> Add support for queries, includes, and excludes flags for codegen

packages/apollo/src/Command.ts
When no config is provided, the URI is resolved to the _parent_ directory because we're not handling that case correctly.
To resolve this, the URI should be set to the filepath itself.
The manifestation of the issue can be seen in the screenshot below. In the current state, we're taking the `.dir`, which is undesirable when `filePath` points to the root of the project.
=> Fix edge case when no config is provided

packages/apollo-language-server/src/schema/providers/introspection.ts, packages/apollo/src/Command.ts, packages/apollo/src/commands/service/download.ts
This restores the skipSSLValidation flag so a schema introspection can be downloaded via http.
For reference: https://github.com/apollographql/apollo-tooling/pull/565
I ran into errors trying to use this^ implementation with `https`. Using `http.Agent` worked for me, though based on the config from the previous implementation I'm curious if I'm overlooking something.
>TypeError [ERR_INVALID_PROTOCOL]: Protocol "http:" not supported. Expected "https:"
Fixes: #728
=> Restore skipSSLValidation flag

packages/apollo/src/commands/client/extract.ts, packages/apollo/src/commands/client/push.ts
The initial implementation of the manifest generation used by `client:push`
and `client:extract` commands was re-using the same AST traversal technique
as that by Apollo Engine Reporting.  That technique removed ALL literals
from the calculated signature.  That technique was primarily employed for
purposes of normalizing operations for use within metric reporting purposes,
but also touted better safety by avoiding shipping literals.
That said, that algorithm removed string, integer, float, list and object
literals - which is a bit more than we'd like to remove for manifest
purposes, where some of those literals have important meaning.
After this commit, we'll still redact string and numeric literals, but
object and list literals (which often contain string and numeric literals,
of course) …
=> Stop excluding object and list literals from operation manifests.

packages/apollo-language-server/src/schema/providers/introspection.ts
Some server implementations return an empty list rather than null in response objects. Added an array size check to introspection to catch cases when an empty `errors` list is returned.
=> Empty 'errors' list in introspection fix

package-lock.json, package.json
As identified in https://github.com/dominictarr/event-stream/issues/116, `event-stream` has a major security issue (malware injection) in version 3.3.6 (thanks to `flatmap-stream` version 0.1.1). `event-stream` 3.3.6 is referenced as a child dep in this project, through `tsc-watch` and `vscode-apollo` / `vscode`.
This commit adds `event-stream` as a top level dependency, and locks it to the most recent version that excludes `flatmap-stream` (version 3.3.4).
This should work for now, but ultimately `tsc-watch` and `vscode` should be updated to newer versions, that address this issue (since their child deps are the problem). Both projects have yet to submit fixes to this problem.
=> Add event-stream as a dep and lock it (security issue)

packages/apollo-language-server/src/project/base.ts
Codegen wasn't working for me with my files ending in ".gql". As my IDE plugin recognizes "*.gql" files as graphql, this is very confusing.
I see two possible further improvements:
1. Warn when including a file without language association
2. Fallback to `graphql` language
=> Associate `*.gql` files with graphql language in GraphQLProject

.vscode/launch.json, packages/apollo-language-server/src/document.ts, packages/apollo-language-server/src/project/base.ts
Now other tags (such as Relay’s `graphql` tag) will actually be recognized with a `apollo.config.js` file like the following:
```js
module.exports = {
client: {
service: {
name: "local",
localSchemaFile: "./data/schema.graphql",
},
includes: ["src/**/*.{ts,tsx,graphql}"],
excludes: ["**/node_modules", "**/__tests__"],
tagName: "graphql",
}
}
```
=> [vscode] Use `tagName` from config to extract documents.

packages/apollo/src/commands/client/codegen.ts
Should be able to set --addTypename to false with --no-addTypename  in apollo client:codegen command.
Follow up for PR #713 
By agreement of @jbaxleyiii
This should resolve Issue #680
=> Allow --no-addTypename in 

packages/apollo-language-server/src/config.ts
- When running the Apollo CLI from a repo that has an `apollo.config.js` file, the config's engine service `name` always took precedence over a passed in `--key` flag and/or environment variables. 
- Make sure that the config loader uses the proper service/client name. 
- If there's a `name` passed in (from `.env` file or from flags), it should overwrite the `client.service`/`service.name` from the loaded file.
=> Fix --key flag/env variable precendece

packages/apollo/src/Command.ts, packages/apollo/src/commands/client/__tests__/__snapshots__/generate.test.ts.snap, packages/apollo/src/commands/client/__tests__/generate.test.ts, packages/apollo/src/commands/client/codegen.ts
This PR re-adds support for providing a custom tagName for `client:codegen`.
Also included:
* Some addition to types
* Tests for `tagName` as a flag and in the config
Fixes: #723
=> Support tagName flag

packages/apollo-tools/src/__tests__/buildServiceDefinition.test.ts, packages/apollo-tools/src/buildServiceDefinition.ts
Directive definitions were discarded when merging types from modules in `buildServiceSchema`.  The fix is nearly trivial, because `Kind.DIRECTIVE_DEFINITION` is a unique case that is neither a schema definition nor a type definition.
=> pass directives from schema modules through buildServiceDefinition

packages/apollo-language-server/src/config.ts, packages/apollo/src/Command.ts
This PR resolves an issue for configless approaches.
A simple reproduction can be achieved by:
```
// .env
ENGINE_API_KEY=...
$ npx apollo service:push --endpoint=<...>
✔ Loading Apollo Project
✖ Uploading service to Engine
→ No service found to link to Engine
```
**Cause**
This is because the `name` was being required before loading the env variables, causing an error to be thrown.
**Solution**
Load the env config earlier in the configuration process so the service name can be inferred if it isn't provided.
=> Fix order of .env loading

packages/apollo/README.md, packages/apollo/src/Command.ts
I updated the CLI docs and apollo readme to note that they are now
specified in the --includes glob.
Fixes #786.
=> Add a note about client schemas

packages/apollo/README.md
I recently updated our Apollo config docs at apollographql.com/docs to cover the config format API, so this PR removes the duplication in `tooling`'s REAME of that API and links to our docs for details instead.
=> Update README to point to the docs for apollo.config.js format

.gitignore
An old build artifact caused test failures. This wasn't immediately
clear because the .gitignore prevented these files from showing up in
the unstaged files. This removes those artifacts to make the fix more
obvious.
=> Remove legacy build artifacts from .gitignore

packages/apollo-language-server/src/config.ts, packages/apollo-language-server/src/project/client.ts, packages/apollo-language-server/src/project/service.ts, packages/apollo-language-server/src/workspace.ts, packages/apollo/src/Command.ts
Multiple streams of work can use this, so breaking out this chunk of work.
The `ApolloConfig` data model should track the URI of its related config file to make that information available when it's needed.
* Add the URI to the data model
* Pass the URI in on construction during `loadConfig`
* Some cleanup / simplification based on things that aren't in use
=> Internally track URI of project config files

package-lock.json, packages/apollo-language-server/src/config.ts, packages/apollo/src/Command.ts, packages/vscode-apollo/create-server-symlink.js
1. The CLI would load a `.env` file containing an `ENGINE_API_KEY`, but the editor integration would not. 
2. If a `type` was not passed into the loadConfig (which happens when run from the editor integration), and the config was a client config, we got into a weird state where all the defaultConfig's were getting merged together.
**For Issue 1:**
* The editor and CLI were both providing a different format for `configPath` (where to look for a `.env`). The editor was passing the dir only (`/User/Jake/my-project`) whereas the CLI was passing the filename (`/User/Jake/my-project/apollo.config.js`).
* The CLI would load the `.env` because it was looking at `configPath.dir` (the parent), but when the config tried to process the same way, it would use the parent of the cwd, giving us a path …
=> Fixed config failing to load .env files for editors

.circleci/config.yml, .vscode/launch.json, packages/apollo/README.md
This PR is mostly a convenience for me, so I have a reference to copy/paste when I'm developing the CLI. But this totally makes sense to document and make easy for other contributors 😄
=> Add documentation and launch task for CLI active development

packages/apollo-language-server/src/config.ts, packages/apollo-language-server/src/fileSet.ts, packages/apollo-language-server/src/languageProvider.ts, packages/apollo-language-server/src/project/base.ts, packages/apollo-language-server/src/project/client.ts, packages/apollo-language-server/src/project/service.ts, packages/apollo-language-server/src/server.ts, packages/apollo-language-server/src/workspace.ts, packages/apollo/src/commands/client/codegen.ts, packages/apollo/src/generate.ts, packages/vscode-apollo/package.json, packages/vscode-apollo/src/extension.ts, packages/vscode-apollo/src/statusBar.ts, packages/vscode-apollo/src/utils.ts
**Client projects when loaded successfully:**
**Error when projects can't load stats (either because of misconfiguration or other language server/extension errors):**
Note: Service projects currently aren't supported for stats, so clicking the status bar icon just prints the extension version and opens the output pane
=> Support status bar command and service stats logging

packages/vscode-apollo/syntaxes/graphql.json
Given the following:
```
launches(
"""
The number of results to show. Must be >= 1.
"""
pageSize: Int = 20
[Completely blank line; no whitespace characters aside from \n]
"""
If you add a cursor here, it will only return results _after_ this cursor
"""
after: String = "hello nurse"
): LaunchConnection!
```
The second comment would be detected and highlighted as a string, not a comment. My formatter removes any additional spaces at the end of lines, so this was a visual nuisance.
Changed from `(?=.)` to `(?=[\n.]` because `.` doesn't take line breaks into consideration.
Hopefully that's the correct place to change this; never created a textmate syntax before.
=> fix(vscode-apollo): Comments not being highlighted correctly

CHANGELOG.md, packages/apollo-language-server/src/config.ts, packages/apollo-language-server/src/project/base.ts, packages/apollo-language-server/src/project/client.ts, packages/apollo-language-server/src/project/service.ts, packages/apollo-language-server/src/schema/providers/index.ts, packages/apollo-language-server/src/server.ts, packages/apollo-language-server/src/workspace.ts, packages/apollo/src/Command.ts, packages/vscode-apollo/package.json, packages/vscode-apollo/src/__tests__/statusBar.test.ts, packages/vscode-apollo/src/extension.ts, packages/vscode-apollo/src/languageServerClient.ts, packages/vscode-apollo/src/statusBar.ts
This PR adds new warning states and communication within the extension in order to help users resolve config issues more easily and know when there's a problem.
Also included with this PR is a bit of a shift in how errors are handled. After speaking with James about it, we both agreed that this would be a scalable approach that will work well with clients consuming the language server or using its parts programmatically.
* Internals of the language server should throw errors, as opposed to catching them and logging at any point.
* The server itself should catch these errors at the top level and message them out via the connection, so they can be consumed by any client listening on that connection.
* Clients using the language server parts programmatically should catch and handle these …
=> [AT-10] Add helpful errors / messaging around config files

packages/apollo/package.json
Pin the dependency since it's currently breaking the CLI
See issue: https://github.com/oclif/config/issues/71
=> Pin @oclif/plugin

CHANGELOG.md, package-lock.json, packages/apollo/package.json
The `apollo-engine-reporting` package previously was causing unresolved peer deps within the `apollo` package. This blocks the upgrade path for some of our users, and is something we should resolve anyway :)
=> Bump the apollo-engine-reporting version

renovate.json
Pin all `apollo` deps via renovate config.
Based on recent experience with packages breaking underneath us, and the typical inherent usage of the CLI being via `npx`, we should pin all deps for the `apollo` package.
For reference, see example 3 in the link below. This decision is also recommended by renovate for our case:
https://renovatebot.com/docs/dependency-pinning/#so-whats-best
=> Update renovate config for apollo package

CHANGELOG.md, packages/apollo-language-server/src/project/client.ts
Filter out 'undefined' definitions before checking the length
It's possible to leave a whole query behind when removing fields by directive. In that case, we want to exclude it altogether. In the current state, definitions can === [undefined], giving a length of 1 and passing this check. By filtering for truthy values only, we won't include empty operations in the result of this function.
TODO:
=> Fix edge case for empty operations

packages/apollo-env/package.json
The API was changed in 3.0.0-beta.12 ([released 2 hours ago](https://github.com/zloirock/core-js/releases)) causing this error in my application:
```
Error: Cannot find module 'core-js/proposals/array-flat-and-flat-map'
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:603:15)
at Function.Module._load (internal/modules/cjs/loader.js:529:25)
at Module.require (internal/modules/cjs/loader.js:657:17)
at require (internal/modules/cjs/helpers.js:22:18)
at Object.<anonymous> (/Users/ben/p/miles/node_modules/apollo-env/src/polyfills/array.ts:1:1)
at Module._compile (internal/modules/cjs/loader.js:721:30)
at Module._compile (/Users/ben/p/miles/example/node_modules/pirates/lib/index.js:83:24)
at Module._extensions..js (internal/modules/cjs/loader.js:732:10)
at Object.newLoader …
```
=> Pin core-js version in apollo-env

CHANGELOG.md, packages/apollo-codegen-scala/src/__tests__/__snapshots__/codeGeneration.ts.snap, packages/apollo-codegen-scala/src/__tests__/types.ts, packages/apollo-codegen-scala/src/codeGeneration.ts, packages/apollo-codegen-scala/src/language.ts, packages/apollo-codegen-scala/src/types.ts, packages/apollo/src/commands/client/__tests__/__snapshots__/generate.test.ts.snap
The change to use traits left some codebases pretty source incompatible, as they depended on APIs that are automatically generated for case classes. This adjusts the codegen to generate similar APIs so that query results have the feel of being case classes without the performance overhead.
=> Improve Scala codegen to make results feel more like case classes

azure-pipelines.yml
To make releases easier and more accessible to others on the team (or for us to do from our phones without being at a computer), I explored the idea of building/releasing the vscode extension via azure pipelines.
**What I did**
- I added a single task to the build pipeline to package the extension (**which I feel we should've been doing anyway**).
- The task produces a build artifact of the `.vsix` file. This file can either be downloaded manually from the `summary` task of an azure build, or used by other pipelines (release pipelines)
- In azure, I set up a release pipeline that is triggered on each successful build. **The release pipeline is created, but not triggered for a deploy**. The release pipeline isn't deployed unless manually queued in the azure UI. I've attached a video on how …
=> Add VS Code build step to azure pipelines CI

package-lock.json, packages/apollo/package.json
Now that `apollo-server-core` is being included in `apollo-engine-reporting` as expected, we can remove it from the listed dependencies.
=> Remove apollo-server-core dep

packages/apollo-language-server/src/config.ts, packages/apollo-language-server/src/server.ts, packages/apollo-language-server/src/workspace.ts, packages/apollo/README.md, packages/vscode-apollo/src/languageServerClient.ts
Remove support for package.json Apollo configuration from vscode extension. For monorepos, supporting this type of configuration causes performance issues during a large file change (git branch change, etc.)
Add documentation and notices around deprecation of package.json support altogether.
TODO:
=> Resolve VS Code + package.json performance concern

CHANGELOG.md, package-lock.json, packages/apollo-language-server/src/engine/index.ts, packages/apollo/src/commands/service/check.ts, packages/apollo/src/utils/__tests__/validateHistoricParams.test.ts, packages/apollo/src/utils/index.ts, packages/apollo/src/utils/validateHistoricParams.ts
This PR adds functionality for 3 new flags in the service:check command:
* validationPeriod - the duration (from now) to validate the service against
* queryCountThreshold - minimum number of requests within the requested time window for a query to be considered
* queryCountThresholdPercentage - number of requests within the requested time window for a query to be considered, relative to total request count.
Also included in this PR - better error messaging:
* Reorders error throwing in `EngineClient`, so that errors reported from the service will be thrown
with priority over the generic "noServiceError" when data isn't present.
TODO:
=> Support validation parameters for service:check

packages/apollo-env/src/polyfills/array.ts, renovate.json
Migrate `core-js/proposals/array-flat-and-flat-map` to `core-js/features/array/{flat|flat-map}`
For reference (from core-js README):
```
core-js(-pure)/es|stable|features/array/flat
core-js(-pure)/es|stable|features/array/flat-map
```
Prevent renovate from updating core-js or @oclif/config via `allowedVersions`.
TODO:
=> Update core-js usage and prevent future updates from renovate.

CHANGELOG.md, packages/vscode-apollo/package.json, packages/vscode-apollo/syntaxes/graphql.js.json
Reference:
https://github.com/vuejs/vetur/issues/701
(Thanks to @flakeparadigm for the original fix and permission to use it)
Pre:
Now:
TODO:
=> Fix inline graphql highlighting in Vue <script>

CHANGELOG.md, packages/apollo/src/commands/service/check.ts, packages/apollo/src/utils/__tests__/validateHistoricParams.test.ts, packages/apollo/src/utils/validateHistoricParams.ts
Previous behavior leveraged the nullability of the checkSchema mutation. By removing defaults from the flags, we can expect the same behavior as before when no historic flags are provided.
*What's incorrect?*
Defaulting to one day for the period was an incorrect assumption on my part - this value can vary on the backend when it's not provided, depending on the user's plan. To account for this, we need the option to provide nothing in the way of historical params (as we were doing before).
TODO:
=> Remove defaults from historic validation

CHANGELOG.md, packages/apollo-codegen-typescript/src/__tests__/__snapshots__/codeGeneration.ts.snap, packages/apollo-codegen-typescript/src/codeGeneration.ts, packages/apollo/src/commands/client/__tests__/__snapshots__/generate.test.ts.snap
tslint is disabled, but eslint is not (yet)
TODO:
=> Add eslint-disable to generated files

package-lock.json, packages/apollo-language-server/src/config/__tests__/config.ts, packages/apollo-language-server/src/config/__tests__/utils.ts, packages/apollo-language-server/src/config/config.ts, packages/apollo-language-server/src/config/index.ts, packages/apollo-language-server/src/config/loadConfig.ts, packages/apollo-language-server/src/config/utils.ts, packages/apollo-language-server/src/engine/index.ts, packages/apollo-language-server/src/schema/providers/engine.ts, packages/apollo/src/Command.ts, packages/apollo/src/commands/client/__tests__/generate.test.ts
This PR brings some sanity to the configuration code. Functionally, it should be a no-op.
* Create a config _folder_, in order to break up `config.ts` into smaller, more manageable parts
* Move utility functions out of `config.ts` into `utils.ts`
* `loadConfig` lives in its own file now, along with related cosmiconfig code
* Remove some duplication
* Clean up functions with some minor TS improvements
> Want to add some tests for util functions, probably will get to that
TODO:
=> Clean up configuration code

CHANGELOG.md, packages/apollo/src/git.ts
With out git loc in the branch call, apollo will fail on schema pushes with the following error: 
```bash
✔ Loading Apollo Project
✖ Uploading service to Engine
→ [git-rev-sync] no git repository found
Error: [git-rev-sync] no git repository found
at _getGitDirectory (/usr/local/lib/node_modules/apollo/node_modules/git-rev-sync/index.js:47:11)
at _getGitDirectory (/usr/local/lib/node_modules/apollo/node_modules/git-rev-sync/index.js:75:10)
at _getGitDirectory (/usr/local/lib/node_modules/apollo/node_modules/git-rev-sync/index.js:75:10)
at _getGitDirectory (/usr/local/lib/node_modules/apollo/node_modules/git-rev-sync/index.js:75:10)
at _getGitDirectory (/usr/local/lib/node_modules/apollo/node_modules/git-rev-sync/index.js:75:10)
at _getGitDirectory …
```
=> Add gitLoc to git.branch

CHANGELOG.md, packages/apollo/src/commands/client/codegen.ts
Resolves #603 
At some point the console log was disabled telling users that types had been updated from codegen in watch mode. This PR is just re-enabling that :)
TODO:
=> Re-enable logging when codegen is in watch mode and detects changes

CHANGELOG.md, packages/apollo-language-server/src/config/loadConfig.ts, packages/apollo-language-server/src/fileSet.ts, packages/apollo-language-server/src/workspace.ts
Fixes 2 bugs:
- VS Code not recognizing a file as being part of the `project` (first commit)
- Changed it from using relative filepath (which is wrong) to use the full path as expected.
- In monorepos, if there are multiple configs, and one fails to load, it won't load _any_ configs.
- Added warning for failed config including path to broken config.
TODO:
=> Fix config loading issues

CHANGELOG.md, package-lock.json, packages/apollo-language-server/src/graphqlTypes.ts, packages/apollo/src/Command.ts, packages/apollo/src/commands/client/check.ts, packages/apollo/src/commands/client/extract.ts
`client:codegen` was defaulting to `--tag=current` when not specifying a flag. That's because there was a default set. It didn't matter if you set another tag in your config, because the CLI flags took precedence over any other configs.
This PR just removes the default _flag_, not the default _tag_. Hopefully this should be non-breaking in any way since the `current` tag fallback is already set other places as a last-resort item.
fallbacks: 
- https://github.com/apollographql/apollo-tooling/blob/master/packages/apollo-language-server/src/config/config.ts#L147
- https://github.com/apollographql/apollo-tooling/blob/master/packages/apollo-language-server/src/engine/operations/schemaTagInfo.ts#L4
- https://github.com/apollographql/apollo-tooling/blob/master/packages/apollo-language-server/src/ …
=> Remove the default --tag flag from client commands

CHANGELOG.md, package-lock.json, packages/apollo/package.json
=> Add @oclif/errors as a dependency of "apollo"

CHANGELOG.md, packages/apollo-codegen-scala/src/language.ts
TODO:
Tests are only there for the general case and not for each single keyword
=> Introduced `type` keyword among the ones that need to be escaped

CHANGELOG.md, package-lock.json, packages/apollo/src/commands/service/check.ts
TODO:
~- [ ] Make sure all of the significant new logic is covered by tests~
=> apigateway: include targetUrl in output

packages/apollo/README.md
I ran into issues with installing the modules, since my packages weren't up to date. This PR adds a note that helped unblock me, curtesy of @trevor-scheer
=> Docs: add note to use npm run clean to troubleshoot install issues

CHANGELOG.md, packages/apollo-env/src/index.ts, packages/apollo-env/src/typescript-utility-types.ts, packages/apollo-language-server/src/config/config.ts, packages/apollo/src/Command.ts
Instead of treating these types as globals, import them directly.
This makes it more straightforward for other projects outside this repo to depend on packages inside this repo (aka if you want to write custom tooling around `apollo-language-server`).
----
TODO:
=> Import apollo-env utility types directly instead of treating them as globals

CHANGELOG.md, package-lock.json, packages/apollo-codegen-flow/package.json, packages/apollo-codegen-scala/package.json, packages/apollo-codegen-swift/package.json, packages/apollo-codegen-typescript/package.json
=> Add missing dependencies "@babel/generator", "common-tags"

CHANGELOG.md, packages/apollo-graphql/package.json
=> Expand peer dependency range of `apollo-graphql` to include 0.12.x and 0.13.x.

package-lock.json, renovate.json
See docs for reference:
https://renovatebot.com/docs/configuration-options/#engines
Only node is supported, and requires a JSON object.
Fixes #1060 
TODO:
=> Fix renovate config

CHANGELOG.md, package-lock.json, packages/apollo/src/commands/service/check.ts
Add a --json flag as an option for output from service:check. This makes the output more easily parsed by other tools.
TODO:
=> JSON flag for service:check output

packages/apollo/src/commands/service/check.ts
The `targetUrl` can be undefined, so we need to ensure it's defined, otherwise we'll print the line without anything actionable 😰
=> apollo: ensure targetUrl is defined when printing

.circleci/config.yml
Right now each CircleCI test run is resulting in different failures.  For
example, each of these were run on the same branch one after each other with
no changes:
* https://circleci.com/workflow-run/60706f8f-1059-496b-a7af-2d24a20d546e
* https://circleci.com/workflow-run/358e33c1-a84a-41ab-9ebd-013507f088f6
* https://circleci.com/workflow-run/89788740-a884-4813-87b3-e4f997362ca9
This is a first step in debugging, and matches the seed pattern used in
other repositories in our organization.
=> Bump CircleCI cache salt to hopefully solve peculiar failures.

renovate.json
This follows up on @trevor-scheer's #951, which switched to exact pinning for all deps in the `apollo` CLI.
As the #951 PR body notes, we want exactly that for `apollo`, however using the `rangeStrategy` of `pin` also includes renovation of the `engines` setting in `package.json`, which we don't want and resulted in https://github.com/apollographql/apollo-tooling/pull/1078 which also exact-pinned `engines` for `node` and `npm`.  (screenshot as it will change after this PR: https://c.jro.cc/ac9256ebf6ae).
I think @trevor-scheer tried to fix this with #889 and #1069, but I believe this would be the more complete solution to that configuration.  It's also worth noting that `lts_active` isn't the version range we wanted to limit to as Node.js 8 is not LTS active, but rather LTS maintenance. …
=> Adjust pinning for `apollo` to not explicitly pin `engines`.

.circleci/config.yml
This was previously disabled (as it is on other repositories), since it
offered some speed benefits.
However, unlikely other repositories, this repo is suffering from a bug with
npm with regard to `.staging` directories and the _Linting_ test seems to be
the one that is failing most often because of `.staging` errors occurring
during the `npm install` step of the _Linting_ job in CircleCI.
This type of failure seems to be fixed in npm@6.9.0, and a local test which
I ran seems to prove that the version of npm that ships with Node.js (which
is what is used by default if we don't run this `run_install_desired_npm`
snippet) exhibits this problem while the latest npm@6.9.0 does not.
=> Also install the latest `npm` version in CircleCI when running Linting.

renovate.json
Per the correct assessment of what we want from the `graphql` package within
the `apollo` package, in the following conversation:
https://github.com/apollographql/apollo-tooling/pull/1078#issuecomment-471099746
Specifically, we're okay using whatever 14.x version of `graphql` is
potentially already available to us when someone installs `apollo` into
their application's `devDependencies` in an existing application.
If the existing application doesn't already have a 14.x version of `graphql`
we will use the latest `14.x` version.
With any success, this will cl_ose #1078 automatically (and not just because
I said "close PR number" in this commit message!).
=> Only `widen` the semver range for the `graphql` dependency of `apollo`.

packages/apollo/src/utils/getOperationManifestFromProject.ts
This PR corrects a previous oversight.
Operation names found during extraction by the language server should be passed along (by the CLI) to the signature function.
Failure to do so would result in publishing the full document, and we would fail to drop unused definitions in the process.
TODO:
=> Pass operation name to the operation registry signature function

packages/vscode-apollo/package.json
The VS Code extension supports graphqls, but we don't list it as such.
=> Add graphqls as a supported file extension for VS Code

packages/apollo-language-server/src/engine/operations/registerOperations.ts, packages/apollo-language-server/src/graphqlTypes.ts, packages/apollo/src/commands/client/push.ts
Now that registerOperations supports version # as an argument to the mutation, we can leverage this for v2 operations manifest work.
This PR finalizes the CLI work to wrap up the sorting fragments bug that lives in v1 of the manifest (currently, the current version of the manifest, but soon to be the previous version).
TODO:
=> Update usage of registerOperations for v2 operations manifest

CHANGELOG.md, packages/apollo/src/__tests__/git.test.ts, packages/apollo/src/commands/client/check.ts, packages/apollo/src/commands/service/check.ts, packages/apollo/src/commands/service/push.ts, packages/apollo/src/git.ts
The remoteUrl can no longer be the slug, since we can't assume that the
feature is going to be used exclusively in GitHub and create an accurate
link the frontend. Additionally we add some logging in order to help
debug.
> Note: My first though was be to make the logging protected by a
verbose flag. Did I miss that functionality?
TODO:
=> apollo: fix remoteUrl in service:check [UI-258]

CHANGELOG.md, packages/apollo-codegen-flow/src/__tests__/__snapshots__/codeGeneration.ts.snap, packages/apollo-codegen-flow/src/printer.ts, packages/apollo/src/commands/client/__tests__/__snapshots__/generate.test.ts.snap
This updates apollo-codegen-flow to strip leading empty lines in flow generated code. This is required to ensure the generated code passes lint, since eslint will only be disabled for all the code after the `/* eslint-disable */` comment.
=> Strip leading empty lines in flow generated code

package-lock.json, packages/apollo/package.json, renovate.json
This latest version should resolve the flaky tests in CI that we've seen 🎉
We can remove the oclif/config exception from the renovate config as well, since everything is pinned.
TODO:
=> Update to latest oclif/config version

CHANGELOG.md, packages/apollo-language-server/src/config/__tests__/loadConfig.ts, packages/apollo-language-server/src/config/loadConfig.ts
- Test the loadConfig functionality
- Document/reorganize the logic
- Bugfixes where discovered by tests
- Fixed bug where a user specifies loading of a config with a flag, but if that file isn't found, it loads an `apollo.config.js`. 
- Ex: `apollo client:check --config=config/apollo.js` would also load `./apollo.config.js` if it couldn't find the specified config. I think if a user is _manually specifying_ a config, it should _only_ load what they specified and throw an error if not found. 
- This was preventing testing errors, since leaving off a config would just load this repo's config (which wouldn't work)
- Removed the `getSearchPlaces` function. It was extraneous, and misleading. While `search places` is the term that dotenv uses, it is less descriptive than `defaultFileNames`, …
=> Add tests for config file loader util

package-lock.json, package.json
Fixes entries in the package-lock file related to @oclif/config. A subsequent `npm install` also cleaned up the `bundled: true` entries which were a result of #1150.
Added `tsconfig.tsbuildinfo` files to the `clean` npm-script, since there's some weirdness with leaving the cache files across `npm install`s that leaves the developer in a bad state.
`npm run clean && npm install`
Fixes #1157
TODO:
=> Update @oclif/config dependency resolution

CHANGELOG.md, packages/apollo-language-server/src/document.ts, packages/apollo-language-server/src/project/base.ts, packages/vscode-apollo/src/languageServerClient.ts
Adds support for vue.  Uses the same extracter as `typescript`/`javacript`/ `___react`.
Just works by adding to list of supported languages.
=> Add vue as supported language to extract gql

CHANGELOG.md, packages/apollo-language-server/src/engine/operations/checkSchema.ts, packages/apollo-language-server/src/graphqlTypes.ts, packages/apollo/src/commands/service/__tests__/check.test.ts, packages/apollo/src/commands/service/check.ts
We use `Listr` to output the progress list (✓s and ✖s). We must pre-fill the titles of the steps that have yet to run. I then change those titles into the correct output. I'd love some feedback on better titles:
```
✔ Loading Apollo Project
⠦ Validating local schema against tag prod on service engine
→ Validating schema
Comparing schema changes
Reporting result
```
---
TODO:
---
=> UI-281 Update schema:check output format

CHANGELOG.md, packages/apollo-language-server/src/graphqlTypes.ts, packages/apollo/src/commands/service/check.ts
In order to have the check details show up, we need to add the git
information to `checkSchema`. This PR adds that back in
=> service:check add git info back

CHANGELOG.md, packages/apollo-language-server/src/engine/operations/checkSchema.ts, packages/apollo-language-server/src/graphqlTypes.ts, packages/apollo/src/commands/service/__tests__/check.test.ts, packages/apollo/src/commands/service/__tests__/fixtures/check-schema-result.json, packages/apollo/src/commands/service/check.ts
This also:
- Adds tests for the singular version of nouns in the markdown. Some were not being pluralized correctly, now we're checking it.
- Replace `'` with backticks in some places
TODO:
This piggybacks on other related PRs; this doesn't need to change the changelog
=> UI-317 Add clients and number of operations checked to markdown output

CHANGELOG.md, packages/apollo/src/commands/service/__tests__/check.test.ts, packages/apollo/src/commands/service/check.ts
Put failures before passes
TODO:
=> Update service:check detailed output order

CHANGELOG.md, package.json, packages/apollo/src/commands/service/check.ts
Also fixes pluralization in the Listr status messages.
All errors thrown will cause Listr to look strange. I was unable to quickly diagnose where the error originates. It exists in prod also so I didn't try too hard to fix it.
TODO:
=> UI-309 Update output for service:checks plan error

package-lock.json, packages/apollo-language-server/src/engine/operations/checkPartialSchema.ts, packages/apollo-language-server/src/graphqlTypes.ts, packages/apollo/package.json, packages/apollo/src/commands/service/check.ts
The purpose of this PR is to update how we display output from the federated `service:check` command. The style of this output resembles recent updates to the output of the standard `service:check` command.
TODO:
=> Update federated service:check output

packages/apollo-language-server/src/engine/index.ts, packages/apollo-language-server/src/engine/operations/removeServiceAndCompose.ts, packages/apollo-language-server/src/graphqlTypes.ts, packages/apollo/src/commands/service/check.ts, packages/apollo/src/commands/service/delete.ts, packages/apollo/src/commands/service/push.ts
- Adds a `service:delete` command _for federated services only_
TODO:
=> Delete federated service

packages/apollo-language-server/src/graphqlTypes.ts, packages/apollo/src/Command.ts
The `--header` flag is supported for all `service` commands that use introspection, but it is required that you use the endpoint flag in order to use the headers. This just adds docs for that.
Related to #700 
TODO:
=> Add documentation for the --header flag

CHANGELOG.md, package-lock.json, package.json, packages/apollo-language-server/package.json, packages/apollo-language-server/src/languageProvider.ts, packages/apollo-language-server/src/server.ts, packages/apollo-language-server/src/utilities/debouncer.ts, packages/apollo-language-server/src/utilities/index.ts, packages/apollo-language-server/src/workspace.ts
The purpose of this PR is to gain a quick performance win in the language server / VS code extension by debouncing and caching a few hot code paths. There may be some better caching wins if we dig deeper into these functions, but for now this is a simple approach that should reduce excessive CPU usage.
TODO:
=> Improve language server performance

CHANGELOG.md, packages/apollo/src/commands/client/download-schema.ts, packages/apollo/src/commands/service/download.ts
Client projects could already download a schema from engine or an endpoint for codegen. This just exposes a command to download a schema to an output file, rather than just keeping it in memory.
I also updated the description for the service:download command and added an error to be more explicit that service:download is supposed to be used for `local` endpoints. Not registry downloads.
TODO:
=> Add ability to download schema to file

packages/apollo/README.md
This PR changes the Slack badge to Spectrum badge
Old:
New:
=> Change Slack to Spectrum in README.md

packages/apollo/src/commands/service/push.ts
Move logging above the call to engine so that logs are still produced in the event of a runtime error
TODO:
=> Debug log before the call out to Engine

CHANGELOG.md, packages/apollo/src/commands/service/check.ts
Currently there isn't an easy way to determine the variables sent to
engine by the apollo service:check command. This adds the ability to
turn on debug mode and print out those commands.
In order to show the statements, run `DEBUG=* apollo service:check`
TODO:
=> apollo: add debug statements to service:check

CHANGELOG.md, packages/apollo/src/commands/client/check.ts, packages/apollo/src/commands/client/push.ts
from #1075
Previously, there was no explicit message stating that engine is a requirement for `client:check` and `client:push` commands.
It'd be easy to mistake these commands as ones that could be run with a `client.service.url` or `localSchemaFile`.
TODO:
=> Document engine requirements in client:check and client:push

package-lock.json, packages/apollo-env/package.json, renovate.json
core-js has officially released v3.x, and the array polyfills we
depend on are marked as stable. We should be able to safely move
away from the beta and unpin the dependency in our renovate config.
See: https://github.com/zloirock/core-js/releases/tag/v3.0.0
Noteworthy change in release notes:
Mark ES2016, ES2017, ES2018, ES2019 features as stable:
Array#{ flat, flatMap }
TODO:
=> Update core-js dependency

CHANGELOG.md, packages/vscode-apollo/syntaxes/graphql.json
Currently vscode highlighting breaks for the entire file when a
graphql defaultValue is used. This is because we don't accept a
close paren or comma as a possible terminator for the
`graphql-variable-assignment` token.
Replace the literal '.' with a closing paren and comma.
TODO:
=> Fix defaultValue parsing

CHANGELOG.md, packages/apollo-codegen-core/src/compiler/index.ts, packages/apollo-codegen-flow/src/__tests__/codeGeneration.ts, packages/apollo-codegen-flow/src/__tests__/helpers.ts, packages/apollo-codegen-flow/src/helpers.ts, packages/apollo-codegen-flow/src/language.ts, packages/apollo-codegen-typescript/src/__tests__/helpers.ts, packages/apollo-codegen-typescript/src/codeGeneration.ts, packages/apollo-codegen-typescript/src/helpers.ts, packages/apollo-codegen-typescript/src/language.ts, packages/apollo/README.md, packages/apollo/src/commands/client/__tests__/__snapshots__/generate.test.ts.snap, packages/apollo/src/commands/client/__tests__/generate.test.ts, packages/apollo/src/commands/client/codegen.ts
Please note that the checks currently fail due to a flaw in the type definitions for `babel-types`, which is fixed in [this PR](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/34926). Once that lands, the tests will pass.
=> Add --useReadOnlyType for TS

CHANGELOG.md, packages/apollo/src/commands/client/push.ts, packages/apollo/src/commands/service/push.ts
This PR adds some debugging statements around the call to our GraphQL api, which will allow us to understand what portions of the stack are misbehaving
=> Add debug print statements around calls to Apollo GraphQL api

CHANGELOG.md, apollo.config.js, packages/apollo-language-server/src/utilities/__tests__/graphql.test.ts, packages/apollo-language-server/src/utilities/graphql.ts
We need operation registration (client:push) `__typename`
adding to match how Apollo Client does this in order for query 
hashes to match.
In order to achieve parity here, I've added the `__typename` field
to InlineFragments as well. While the `__typename` on an interface
may be redundant (see new tests for example), it's also a safer
change for me to recommend than anything within Apollo Client.
TODO:
=> Fix __typename addition for InlineFragments

packages/apollo/src/commands/client/push.ts
Recent logging introduced a runtime error for `client:push` by attempting to log an undefined variable. This PR simply logs the correct variable as was previously intended.
TODO:
=> Fix logging to the correct operations variable

package-lock.json, packages/apollo-language-server/package.json, packages/apollo/package.json
An incoming graphql release (14.3.1) is going to break at least
`apollo client:check` as it did in the past with `14.2.0` (confirmed this
manually with graphql's master branch). This dependency restriction
will prevent this for now, without us needing to find the root of
the issue. This is preventative until we have the resources
to investigate and resolve the actual cause of the problem.
For more details and full context, see:
https://github.com/graphql/graphql-js/commit/183ff32bee4bc23eb23657f79f414c2400ecb06a#r32971387
cc @abernix @martijnwalraven
TODO:
=> Pin graphql to the ~14.2.x range

CHANGELOG.md, packages/apollo-language-server/src/config/config.ts, packages/apollo-language-server/src/engine/index.ts
The stats window is seemingly assigned to an invalid type
TODO:
=> apollo-language-server: Update stats window types

CHANGELOG.md, packages/apollo-language-server/src/engine/index.ts, packages/apollo-language-server/src/engine/operations/registerOperations.ts, packages/apollo-language-server/src/graphqlTypes.ts, packages/apollo/src/commands/client/push.ts, packages/apollo/src/commands/service/check.ts, packages/apollo/src/utils/index.ts, packages/apollo/src/utils/pluralize.ts
This updates the operation registration command to use the new resolver
that returns more information, namely added operations and invalidation
messages associated with the operation. The `apollo client:push` command
then outputs this information
Happy path:
Sad path:
TODO:
=> apollo client:push update output to include more details

CHANGELOG.md, packages/apollo-codegen-core/src/loading.ts, packages/apollo-language-server/src/config/config.ts, packages/apollo-language-server/src/config/loadConfig.ts, packages/apollo-language-server/src/diagnostics.ts, packages/apollo-language-server/src/errors/validation.ts, packages/apollo-language-server/src/project/client.ts, packages/apollo/src/defaultValidationRules.ts
Closes #1056
(I didn’t find any test coverage for the areas I touched, but am pretty sure my additions are backwards compatible.)
=> [language server] Allow configuration of validation rules.

package-lock.json, packages/apollo-language-server/package.json, renovate.json
vscode-uri introduced a breaking change in v1.0.7
For now, we'll pin the package to the previous patch.
Fixes #1305
See: https://github.com/microsoft/vscode-uri/commit/7f15d244457fd4e09c88264c676dc915beffb634
TODO:
=> Pin vscode-uri v1.0.6

renovate.json
Pending further investigation into graphql changes, we want the
graphql version of apollo and the language server to be "pinned"
to ~14.2.1.
For reference on _why_ we want this (for now), see: https://github.com/apollographql/apollo-tooling/pull/1291
This PR should close the renovate's PR: #1303 (automatically,
not via GitHub)
TODO:
=> Update renovate config for graphql

CHANGELOG.md, packages/apollo-language-server/src/engine/operations/registerOperations.ts, packages/apollo-language-server/src/graphqlTypes.ts, packages/apollo/src/commands/client/push.ts
This PR passes the `graphVariant` argument to the `registerOperations` mutation
TODO:
(https://github.com/mdg-private/monorepo/pull/2338 need to be released to prod before this can be released)
=> Add tag awareness to client:push

CHANGELOG.md, packages/apollo-graphql/src/schema/__tests__/buildSchemaFromSDL.test.ts, packages/apollo-graphql/src/schema/buildSchemaFromSDL.ts
Add support for meta resolvers on abstract types.
Fixes: https://github.com/apollographql/apollo-server/issues/2781
TODO:
=> buildSchemaFromSDL - support meta fields on abstract types

CHANGELOG.md, packages/apollo-language-server/src/utilities/debouncer.ts
Previously the debouncer was configured as `trailing`, which meant that the first `n-1` calls in a batch of `n` calls would get old data, and the last one would get new data.
Practically speaking, this meant that a new call for completion items would give the results of the last call for completion items, and a user could only get updated completion items after calling for them twice, more than 400ms apart.
This fixes that by setting the debouncer to be `leading`, which means that the first call in a new batch executes, and the remaining calls in the batch get it's results.
TODO:
=> Fix bug causing completion handlers to sometimes return old results

CHANGELOG.md, packages/apollo-graphql/src/schema/__tests__/buildSchemaFromSDL.test.ts, packages/apollo-graphql/src/schema/buildSchemaFromSDL.ts, packages/apollo-graphql/src/schema/resolverMap.ts
As described in #1343 and #1344, it is better to use `addResolveFunctionsToSchema` from graphql-tools to add the resolvers to the new schema, as it is how the resolvers are added normally in apolo-server, so that both scalars and enums are handled properly. As a TODO, it might be sensible to use more functionality from https://github.com/apollographql/graphql-tools/blob/84e77ac7d7e06f149019c5a42dd2e86907e27ac1/src/makeExecutableSchema.ts when generating the new schema.
TODO:
=> Add support for custom enum resolvers and scalar types

CHANGELOG.md, packages/apollo/src/commands/service/list.ts
The time is relative; over time the value changes, causing the snapshot to
fail.
TODO:
=> Fix service:list snapshot relative time

CHANGELOG.md, packages/apollo/src/commands/service/__tests__/__snapshots__/list.test.ts.snap, packages/apollo/src/commands/service/list.ts
As I was writing docs, I realized that `service:list` has no list headers. I think these are necessary for understanding. Added in this PR. 
Also sorting alphabetically as requested in the [federation docs](https://github.com/apollographql/apollo/pull/504)
TODO:
=> add header to service list

CHANGELOG.md, packages/apollo-language-server/src/document.ts, packages/apollo-language-server/src/project/base.ts, packages/vscode-apollo/package.json, packages/vscode-apollo/src/languageServerClient.ts, packages/vscode-apollo/syntaxes/graphql.rb.json
As the title says, this adds support for Ruby projects that use `<<-GRAPHQL…GRAPHQL` heredoc strings to define GraphQL documents.
An example can be found here https://github.com/artsy/exchange/pull/413
=> [language server/vscode] Add Ruby support

CHANGELOG.md, packages/apollo-tools/src/__tests__/buildServiceDefinition.test.ts, packages/apollo-tools/src/buildServiceDefinition.ts, packages/apollo-tools/src/schema/resolverMap.ts
This PR adds a handler and typing for resolvers for Subscriptions
As Jesse helped find in graphql-tools, [resolve and subscribe are not mutually exclusive](https://github.com/apollographql/graphql-tools/blob/641d7058fdf4b7af08a92a770c0b9a4f0febea29/src/stitching/mergeSchemas.ts#L259-L272)
I believe this relates to https://github.com/apollographql/apollo-server/issues/2149
TODO:
=> Handle `subscribe` in resolverMap

CHANGELOG.md, packages/apollo/src/commands/client/__tests__/__snapshots__/generate.test.ts.snap, packages/apollo/src/generate.ts
Xcode expects newline terminated files as noted in https://github.com/apollographql/apollo-ios/issues/531. I found this related PR https://github.com/apollographql/apollo-tooling/pull/525/, so maybe a more generic solution should be considered.
This is my first contribution to this project, let alone my first lines of TypeScript, but I hope its intention comes across.
=> Append terminating newline to output

packages/apollo/src/Command.ts, packages/apollo/src/commands/service/push.ts
* Do not require users to specify `--federated` as long as `--serviceName` is provided
* Change error messages for lack of full specification to point to how to remedy the problem
* Provide step-by-step output logging information regarding which aspect of service:push succeeded or failed
TODO:
=> [Federation] service:push, user experience improvements

CHANGELOG.md, packages/apollo-codegen-swift/src/__tests__/__snapshots__/codeGeneration.ts.snap, packages/apollo-codegen-swift/src/codeGeneration.ts, packages/apollo/src/commands/client/__tests__/__snapshots__/generate.test.ts.snap
Updates Swift codegen to add the operation name to generated query classes. 
TODO:
=> [airbnb] Update Swift codegen to add operation name to generated query classes

CHANGELOG.md, packages/apollo/src/commands/service/__tests__/__snapshots__/check.test.ts.snap, packages/apollo/src/commands/service/__tests__/check.test.ts, packages/apollo/src/commands/service/check.ts
Support `--markdown` and `--json` flags for `apollo schema:check` command. Reintroduce tests and update snapshots.
Also refactor `check.ts` slightly, including renaming `serviceName` to `graphName` in markdown output now that there is a more pronounced difference between the terms with federation.
TODO:
=> Support --json and --markdown for federated schema:check

packages/apollo/src/commands/service/push.ts
While we _do_ want to make the change to using variant internally and externally, we've decided to hold off on this switch for now. Changing this label back to `tag` will keep us consistent until we decide to make the change.
TODO:
=> Revert back to 'tag' for now

CHANGELOG.md, packages/apollo/src/commands/service/push.ts
In line with how we handle errors elsewhere in `service:check` and `service:push`, the CLI should exit status code 1 when composition errors are encountered in order to fail CI/CD which uses this command.
TODO:
=> Exit status code 1 after composition errors in service:push

CHANGELOG.md, packages/vscode-apollo/src/statusBar.ts
"Apollo GraphQL" is a little verbose for the limited space on the status bar. This just renames it to "Apollo"
TODO:
=> Change status bar name

CHANGELOG.md, packages/vscode-apollo/package.json
Activating the extension on `package.json` is potentially obnoxious for non-apollo projects, and breaks for projects that don't use a package file. Activating on `apollo.config.js` works across all project types and keeps the extension quiet for non-apollo projects.
TODO:
=> Only activate extension on apollo.config.js/ts

CHANGELOG.md, packages/apollo-language-server/src/engine/index.ts, packages/apollo-language-server/src/project/client.ts, packages/apollo-language-server/src/providers/schema/engine.ts, packages/apollo/src/index.ts
Right now, there's no error being printed when schema lookup fails. 
This PR aims to fix that, and add at least a safeguard for people using incorrect API keys. This can be partially checked on the client by checking the `config.service.name` against the identifier in the API key.
See the comments in the file changes for more explanation.
For the future, we really should standardize our error strategy to make sure they're being printed prettily in the editor. Right now, we're getting some pretty ugly stack traces.
TODO:
=> Add helpful message for invalid API key

CHANGELOG.md, packages/apollo-codegen-swift/src/__tests__/language.ts, packages/apollo-codegen-swift/src/codeGeneration.ts, packages/apollo-codegen-swift/src/language.ts
Resolves #1177. The goal is to prevent compiler warnings for redundant access-level modifiers when using `--namespace`.
It covers queries and fragments, according to basic testing at least, resolving the initial issue. Are there more types affected by this? @martijnwalraven
=> Skip redundant modifiers

CHANGELOG.md, packages/apollo-language-server/src/document.ts, packages/apollo-language-server/src/project/base.ts, packages/vscode-apollo/package.json, packages/vscode-apollo/src/languageServerClient.ts, packages/vscode-apollo/syntaxes/graphql.dart.json
This resolves #1365.
Similar to how python handles this, adding support for graphql syntax highlighting and code completion using a basic function.
```dart
String gql(String x) => x;
var query = gql(r"""
query getPeople {
allPeople {
people {
id
birthYear
created
}
}
}
""");
```
Screenshot of it in action:
I need a bit of guidance on building and testing the extension locally (including the language server). What's the process developers are typically using on `vscode-apollo`?
In order to test the functionality out, I patched the extension and language server directly in `/Users/venkat/.vscode/extensions/apollographql.vscode-apollo-1.7.4`. Then I applied those same changes to this repo. However I'd like to double check it all works.
=> Dart support for vscode-apollo and language-server

CHANGELOG.md, packages/apollo-language-server/src/workspace.ts
Resolves #1446 
When I stepped through the debugger I noticed that the cache wasn't getting properly cleared which resulted in outdated autocomplete results. Adding cache clearing to`project.reloadSchema` appears to resolve the issue.
=> Clear projectForFileCache when schema is reloaded

CHANGELOG.md, packages/apollo-codegen-swift/src/__tests__/__snapshots__/codeGeneration.ts.snap, packages/apollo-codegen-swift/src/__tests__/codeGeneration.ts, packages/apollo-codegen-swift/src/__tests__/language.ts, packages/apollo-codegen-swift/src/language.ts
This fix addresses [iOS 193](https://github.com/apollographql/apollo-ios/issues/193), where the name of the parameter was being escaped in a property, but the name of the type was not. 
Also made sure the names of classes are being properly escaped, and the names of parameters on protocol property declarations.
Note: I've left the type unescaped on protocol properties purposely, because I'm not sure if we're using `Self` as a bound anywhere, and I'd like to fix the other stuff without breaking the crap out of that.
=> [Swift] Fix escaping of parameter and class names

CHANGELOG.md, packages/apollo-codegen-swift/src/__tests__/codeGeneration.ts, packages/apollo-codegen-swift/src/__tests__/language.ts, packages/apollo-codegen-swift/src/codeGeneration.ts, packages/apollo-codegen-swift/src/language.ts
#1449 Pointed out that #1241 introduced a regression when files are being output individually. This PR updates our logic to make sure that information is shared and then fix the issue.
=> Swift: Fix regression for individual files. 

CHANGELOG.md, packages/apollo-codegen-swift/src/__tests__/__snapshots__/codeGeneration.ts.snap, packages/apollo-codegen-swift/src/__tests__/codeGeneration.ts, packages/apollo-codegen-swift/src/codeGeneration.ts, packages/apollo-codegen-swift/src/language.ts, packages/apollo/src/commands/client/__tests__/__snapshots__/generate.test.ts.snap
In this PR: 
- Added `CaseIterable` conformance to `enum` types so all known cases can be easily iterated.
- Added comments with the original fragment or query definition to `operationDefinition` and `fragmentDefinition`
- Trimmed out excess whitespace from the final strings sent to the server for `operationDefinition` and `fragmentDefinition`
- Removed force-unwrap when the thing being unwrapped is a double optional
Note to tooling team: When this gets merged it should be released as minor-version alpha so I can make sure everything works well against our API and I haven't missed anything. 
Also I am teh suck at typescript so would love any suggestions on how to do stuff better.
=> Swift Codegen Upgrades

packages/apollo-codegen-swift/src/__tests__/__snapshots__/codeGeneration.ts.snap, packages/apollo-codegen-swift/src/codeGeneration.ts
This is a solution to the problem described here:
> We have generated a Swift API for a schema that includes an interface.
>
> When we now add an additional type that implements this interface to the server, the app crashes. This can of course be fixed by regenerating the api, but this doesn't help for apps already running on a user's device.
> https://github.com/apollographql/apollo-ios/issues/400
I'm not sure if this is the only place where this filtering has to be done, but this at least fixes it for our use case.
=> filter objects in getter to only include known typenames

CHANGELOG.md, packages/apollo-codegen-swift/src/__tests__/__snapshots__/codeGeneration.ts.snap, packages/apollo-codegen-swift/src/codeGeneration.ts
This PR reverts changes from #656, they were causing build issues on iOS and the originator is going to come up with a new reproduction before we take another stab at this. 
This will need to go out as a patch release for `swift` and `tooling` since I ~~'m a moron~~ got a little ahead of myself and didn't fully test these locally before getting them released.
=> Revert PR #656

CHANGELOG.md, packages/apollo-language-server/src/config/config.ts
resolves #881
Previously, when initializing an `ApolloConfig` class, we were pulling the `dirname` properly off the file path of a `.js` config file, but we weren't handling the case of the config filepath being a `.ts` file at all (oops).
This change should fix the dirname parsing for all files that we support.
TODO:
=> Fix config path parsing with ts files

CHANGELOG.md, packages/apollo-language-server/src/providers/federation-info/endpoint.ts, packages/apollo-language-server/src/providers/schema/introspection.ts
=> correct implementation of ignore https verification

CHANGELOG.md, packages/apollo-language-server/src/project/client.ts, packages/apollo-language-server/src/utilities/__tests__/graphql.test.ts, packages/apollo-language-server/src/utilities/graphql.ts
We're getting `client:check` failures when using a `Fragment `in a `@client` field because while the fields with `@client` are stripped, `Fragment`s that are nested below them are not. We now check that `Fragment`s can be removed if they are only used in `@client` fields.
I added tests to the existing functionality on one commit, added a failing test for how I expected the method to behave, and then fixed the test. Please look at the last new test to see a reproduction.
---
TODO:
=> AP-682 Strip `FragmentDefinition`s in `client:check` when only included in `@client` fields

CHANGELOG.md, packages/apollo-language-server/src/config/__tests__/loadConfig.ts, packages/apollo-language-server/src/config/loadConfig.ts, packages/apollo-language-server/src/index.ts, packages/apollo-language-server/src/server.ts, packages/apollo-language-server/src/utilities/debug.ts, packages/apollo-language-server/src/utilities/index.ts, packages/apollo-language-server/src/workspace.ts, packages/apollo/src/Command.ts, packages/vscode-apollo/src/debug.ts, packages/vscode-apollo/src/extension.ts
This PR is the result of investigating how other implementations of the language server protocol handle errors. This PR proposes a new method of handling errors across the language server and its clients (CLI and VS Code). The intention is to produce a more friendly, consistent means by which to log and handle errors, as well as set up the basis for what could become usage metrics and error reporting, and verbose/debugging modes.
- No control over the granularity of errors (full stack traces, all the time)
- No proper debug logging mechanism to help trace errors.
- No standard way to log normal messages/warnings from the language server to all clients
- Most language server implementations don't fail out. If an operation is unsuccessful, they just return an empty response, and the clients …
=> Standardize language server errors

CHANGELOG.md, packages/apollo-language-server/src/project/base.ts, packages/apollo-language-server/src/project/client.ts
Currently, the `apollo-language-server` requires operation names in a client project to be unique in order to properly generate types, but this isn't enforced by an error. This PR adds an error so the user is aware of a name collision. 
When generating a type using codegen, if there are duplicate type names, only one of the operations will get types generated. this error will enforce the already designed intention of the CLI.
The following screenshot shows the error as well as showing that **the error doesn't interfere with `--watch` mode**.
resolves #1427
TODO:
=> Error with duplicate operation names

CHANGELOG.md, package-lock.json, package.json, packages/apollo/src/Command.ts, packages/apollo/src/commands/client/check.ts, packages/apollo/src/commands/service/__tests__/__snapshots__/check.test.ts.snap, packages/apollo/src/commands/service/__tests__/check.test.ts, packages/apollo/src/commands/service/check.ts, packages/apollo/src/utils/CompactRenderer.ts, packages/apollo/src/utils/index.ts
=> Shorten client:check and service:check output in CI 

packages/apollo-language-server/src/graphqlTypes.ts
Update generated types due to schema changes.
This is a result of:
`npm run client:codegen`
=> Update codegen types

package-lock.json, package.json, renovate.json
> In the same spirit as `apollo-server`:
> https://github.com/apollographql/apollo-server/commit/585085d4d8dd7ab
Thanks to a gracious fix to Lerna by the Babel community, this issue
(originally reported in my https://github.com/lerna/lerna/issues/2107) is no
longer an issue in new versions of Lerna, thanks to the fix provided in
https://github.com/lerna/lerna/pull/2185.
Ref: https://github.com/lerna/lerna/pull/2185
Ref: https://github.com/lerna/lerna/issues/2107
cc @JakeDawkins
cc @trevor-scheer
=> Stop pinning Lerna to pre v3.14.0.

.circleci/config.yml, lerna.json, package.json
In the same spirit as the following PRs from Apollo Server:
* https://github.com/apollographql/apollo-server/pull/3246
* https://github.com/apollographql/apollo-server/pull/3245
* https://github.com/apollographql/apollo-server/pull/3254
Check out those PRs for more details!
But, in a nutshell:
1. `npm run release:version-bump`
This should behave the same as `npm run release` did previously, except rather than doing the actual publish, it will only bump the versions and push the tags to CircleCI.
2. `npm run release:start-ci-publish`
This will create and push a `publish/{timestamp}` tag to CircleCI which will kick off the actual publish pipeline.
...and the rest should happen in CircleCI!  A notification will be sent to Slack when the _Confirmation_ step is pending approval, and also when …
=> Automate publishing via Git tag triggered CircleCI workflow.

CHANGELOG.md, packages/apollo-codegen-core/src/compiler/index.ts, packages/apollo-codegen-core/src/serializeToJSON.ts, packages/apollo-codegen-core/src/utilities/graphql.ts, packages/apollo-codegen-flow/src/codeGeneration.ts, packages/apollo-codegen-flow/src/helpers.ts, packages/apollo-codegen-scala/src/codeGeneration.ts, packages/apollo-codegen-scala/src/naming.ts, packages/apollo-codegen-scala/src/types.ts, packages/apollo-codegen-swift/src/codeGeneration.ts, packages/apollo-codegen-swift/src/helpers.ts, packages/apollo-codegen-typescript/src/codeGeneration.ts, packages/apollo-codegen-typescript/src/helpers.ts, packages/apollo-language-server/src/languageProvider.ts, packages/apollo-language-server/src/utilities/graphql.ts
This replaces all `instanceof GraphQLXYZ` checks with their respective predicate functions.
TODO:
=> Replace instanceof checks with their respective predicates

CHANGELOG.md, packages/apollo-codegen-core/src/utilities/CodeGenerator.ts, packages/apollo-codegen-swift/src/__tests__/__snapshots__/codeGeneration.ts.snap, packages/apollo-codegen-swift/src/__tests__/codeGeneration.ts, packages/apollo-codegen-swift/src/__tests__/language.ts, packages/apollo-codegen-swift/src/codeGeneration.ts, packages/apollo-codegen-swift/src/helpers.ts, packages/apollo-codegen-swift/src/language.ts
The source generator now operates using a string wrapper type called `SwiftSource`. Identifiers are escaped when converting into `SwiftSource` values, with an alternative method for producing escaped string literals. An escape hatch is provided for disabling escapes, but the default behavior is to escape all identifiers in the dynamic input.
Most `SwiftSource` values are produced by a tagged template literal, which allows for easy mixing of string literals containing Swift keywords and dynamic input that needs escaping.
As part of this, rewrite string escaping such that it actually escapes string contents properly. This required fixing a test that had a bad spec enforcing broken behavior.
Fixes apollographql/apollo-ios#193.
Fixes apollographql/apollo-ios#752.
---
This PR isn't quite done …
=> Fix Swift codegen escaping for identifiers, types, and strings

.circleci/config.yml
Two steps in the CI process are reliant on the `CHECKS_API_KEY` env variable. Since this isn't available on runs that are triggered by a fork, those tasks would error out.
This PR skips those commands that requires a env variable which is private.
This is still safe to do, since once merged to master, the checks would be run again, but with those env variables present. And it would be run once again before a release. So the missing check in the PR isn't critical for preventing failures.
TODO:
=> Skip jobs that need API keys on forks

.circleci/config.yml
This adds a tarball build step for packaging up the CLI.
This PR does not yet _publish_ that tarball anywhere, but it does store it as an artifact of the build under the `artifacts` tab in Circle
TODO:
=> Add CLI Build Step to Circle (non-deploy)

packages/apollo-language-server/src/config/config.ts, packages/apollo-language-server/src/providers/schema/index.ts, packages/apollo/src/Command.ts, packages/apollo/src/commands/client/codegen.ts, packages/apollo/src/commands/service/check.ts, packages/apollo/src/commands/service/push.ts
Because of how oclif handles flags, it was possible to incorrectly parse a command with multiple `--localSchemaFile` flags like the following:
`apollo client:codegen --target=swift --localSchemaFile=schema.graphql API.swift`
This command would parse the last `<output>` argument as a schema and fail to parse. This is a bug that currently exists in oclif with how `multiple: true` flags are parsed.
https://github.com/oclif/oclif/issues/190#issuecomment-486473267
This PR changes flag parsing to only accept a single flag for `localSchemaFile`, allowing for a comma-separated-list of schema files like:
```
apollo client:codegen --target=swift --localSchemaFile=schema.graphql,schema2.graphql API.swift`
```
TODO:
\*Make sure changelog entries note which project(s) has been affected. See older …
=> Fix multiple localSchemaFile bug

packages/apollo-codegen-swift/src/__tests__/__snapshots__/codeGeneration.ts.snap, packages/apollo-codegen-swift/src/__tests__/language.ts, packages/apollo-codegen-swift/src/language.ts
This PR updates #1537 to emit multiline string literals more correctly, and enables the use of multiline string literals even when the source text includes the `"""` token.
=> [swift] Improve multi-line string literal usage

CHANGELOG.md, package-lock.json, package.json, packages/apollo/@types/heroku-cli-util.d.ts, packages/apollo/package.json, packages/apollo/src/commands/client/push.ts, packages/apollo/src/commands/service/__tests__/__snapshots__/check.test.ts.snap, packages/apollo/src/commands/service/__tests__/__snapshots__/list.test.ts.snap, packages/apollo/src/commands/service/check.ts, packages/apollo/src/commands/service/list.ts, packages/apollo/src/commands/service/push.ts
Federation results in particular can be quite long, causing some
word wrap pandemonium. This package supports word wrap and a
provides a cleaner look overall for tabular output.
This PR does _not_ replace all usages of `heroku-cli-util`s `table` function.
For output that is currently untested or that I couldn't test manually, I didn't
make the switch.
Successful `service:check`
Failing `service:check`
`service:list`
Successful `service:push`
Failing `service:push`
TODO:
=> Use "table" package for tabular output and word wrap support

CHANGELOG.md, packages/apollo-codegen-core/src/compiler/index.ts, packages/apollo-codegen-swift/src/__tests__/__snapshots__/codeGeneration.ts.snap, packages/apollo-codegen-swift/src/__tests__/codeGeneration.ts, packages/apollo-codegen-swift/src/__tests__/language.ts, packages/apollo-codegen-swift/src/codeGeneration.ts, packages/apollo-codegen-swift/src/language.ts, packages/apollo/README.md, packages/apollo/src/commands/client/__tests__/__snapshots__/generate.test.ts.snap, packages/apollo/src/commands/client/codegen.ts, packages/apollo/src/generate.ts
In this PR there are a few changes to the Swift codegen: 
- Defaulted to printing queries as multi-line string literals to make sure the queries match the SHA256 hash being generated in `operationIdentifier`
- Added `--suppressSwiftMultilineStringLiterals` flag which defaults to false if you'd rather strip out all whitespace. 
- Removed comments showing the query since this is now covered by multi-line string literals
=> [swift] Use multi-line string literals for queries

CHANGELOG.md, packages/apollo-codegen-core/package.json, packages/apollo-codegen-flow/package.json, packages/apollo-codegen-scala/package.json, packages/apollo-codegen-swift/package.json, packages/apollo-codegen-typescript/package.json, packages/apollo-language-server/package.json, packages/apollo-language-server/src/engine/index.ts, packages/apollo-language-server/src/engine/operations/checkPartialSchema.ts, packages/apollo-language-server/src/graphqlTypes.ts, packages/apollo/README.md, packages/apollo/package.json, packages/apollo/src/commands/service/__tests__/__snapshots__/check.test.ts.snap, packages/apollo/src/commands/service/__tests__/check.test.ts, packages/apollo/src/commands/service/check.ts, packages/vscode-apollo/package.json
Several months ago, we implemented a mutation called
`checkPartialSchema`, which was designed to encapsulate both checking
for ability to compose and validating schema changes against operations.
This new mutation has several added benefits, like displaying a new
webpage with better information for federation users, along with
allowing users to see multiple status lines appear in their PRs when
using the GitHub integration. This PR attempts to migrate to use the
newer mutation, abandoning the old. There were some sad moments trying
to fight against the automatic type generation, so please forgive me
if anything is not quite right type-wise, and please take over this
commit at will. I have yet to test it locally, but I figured that
this could at the very least get the ball rolling, and I'm …
=> Modify service:check command to use combined mutation

CHANGELOG.md, packages/apollo-graphql/src/schema/buildSchemaFromSDL.ts
Similar in spirit to https://github.com/apollographql/apollo-server/pull/3338.
The technique previously used for removing rules from the standard `specifiedRules` was leveraging a check on `Function.prototype.name`, rather than doing direct object equality.  While that does generally work, thanks to the more recent standardization of `Function.prototype.name`, it still breaks down under some of the more aggressive minification techniques since a function's name is not guaranteed to remain the same.
Fixes: https://github.com/apollographql/apollo-server/issues/3335
=> Use reference-equality when filtering rules in `buildSchemaFromSDL`

packages/apollo-codegen-core/package.json, packages/apollo-codegen-flow/package.json, packages/apollo-codegen-scala/package.json, packages/apollo-codegen-swift/package.json, packages/apollo-codegen-typescript/package.json, packages/apollo-graphql/package.json, packages/apollo-language-server/package.json, packages/apollo/README.md, packages/apollo/package.json, packages/apollo/src/commands/service/check.ts, packages/vscode-apollo/package.json
=> Add gitContext to checkPartialSchema mutation

CHANGELOG.md, packages/apollo-codegen-swift/src/__tests__/__snapshots__/codeGeneration.ts.snap, packages/apollo-codegen-swift/src/__tests__/codeGeneration.ts, packages/apollo-codegen-swift/src/codeGeneration.ts, packages/apollo-codegen-swift/src/helpers.ts, packages/apollo-codegen-swift/src/language.ts
When a field is named `self`, escaping it with backticks (e.g. <code>\`self\`</code>) when used as a method parameter is not sufficient, as Swift interprets the escaped identifier the same as the keyword. Instead we need to synthesize a safe internal parameter name. This PR picks `_self` by default, but checks for conflicts and will go with `_self_`, `_self__`, etc. until it finds a unique name.
I've updated all of the logic I can find that emits initializers to do this, but my tests only cover some of this as I'm not sure when the other code is used.
This PR also fixes a bug where leading/trailing underscores were being stripped, so e.g. a field named `_foo` would show up as just `foo` in the generated code. This is a breaking change, which but it's unlikely to affect many people.
Fixes …
=> swift: Fix initializers with field named `self`

CHANGELOG.md, packages/apollo-codegen-swift/src/codeGeneration.ts, packages/apollo/src/commands/client/__tests__/__snapshots__/generate.test.ts.snap
Hi folks! The Swift code-gen today requires that an Objective-C umbrella header be present that has an `import <UIKit/UIKit.h>` to compile. You can see this for yourself by running code-gen on any request/response that has a `Date` as a value or parameter. `Date` comes from `Foundation`, but there is no import of `Foundation`. Instead, the generated code implicitly relies on the `UIKit` import from an umbrella header to pull in `Foundation`.
This PR explicitly imports `Foundation` in the generated code, which allows consumers of Swift Apollo code-gen to no longer need an umbrella header.
TODO:
=> Import Foundation in codegen

.gitignore, CHANGELOG.md, packages/apollo-language-server/src/engine/operations/checkPartialSchema.ts, packages/apollo-language-server/src/graphqlTypes.ts, packages/apollo/src/commands/service/check.ts
This passes the already in memory frontend and historic parameters to the federated service check
=> support frontend and historic parameters for service:check with federation

.circleci/config.yml
Previously, to work around the dually-incompatible combination of oclif and
lerna, the process of publishing a oclif packed tarball of the `apollo` CLI
for use by the Apollo iOS SDK, this process was using `npm install apollo` in
a temp directory, generating a lock-file from that, and then running
`oclif-dev pack` on that after jocking those installed artifacts into Lerna.
This approach resulted in the artifact that was published to CircleCI being
only a build of what was currently published to npm which, aside from being
confusing and unclear to the untrained eye, also just doesn't provide the
benefit of being able to run a build and test its tarball in isolation,
without a more complete publish.
By introducing an [additional job and some commands][Ref] to our CircleCI orbs,
this makes …
=> Build Oclif from packages published to Verdaccio rather than npm.

CHANGELOG.md, packages/apollo/src/commands/client/codegen.ts
resolves #1584 
#1559 introduced an issue where the documents from files were not being invalidated on change, so codegen in watch mode would not update types on save.
TODO:
=> Fix codegen --watch not seeing operation changes

CHANGELOG.md, packages/apollo-language-server/src/server.ts, packages/apollo-language-server/src/utilities/debouncer.ts
This is an incremental improvement to the autocomplete handling in the language server. this is _not_ a 100% fix for all of the issues in autocomplete but hopefully _is_ a complete fix for the ctrl+space recommendations in vscode.
Ctrl+space and autocomplete right now doesn't work properly. The recommended options are showing the fields for the parent type.
This is because of the `leading: false` option being passed to the debounce function. In addition, this PR reduces the debounce timeout to make other issues with autocomplete less obvious 
TODO:
=> Fix debouncing issue in vscode autocomplete

CHANGELOG.md, packages/apollo-codegen-swift/src/__tests__/codeGeneration.ts, packages/apollo-codegen-swift/src/codeGeneration.ts, packages/apollo-codegen-swift/src/helpers.ts, packages/apollo-codegen-swift/src/language.ts
The codegen was omitting the `[:]` and `[]` tokens entirely.
Fixes apollographql/apollo-ios#838
The root cause of missing `[:]` was there was some code relying on the truthy value of strings, but the conversion to `SwiftSource` caused even empty sources to become truthy. I'm actually surprised TypeScript happily accepts `someObject || someStr` and evaluates it as the object type with no warnings (I mean, it will always be the object type, but the `|| someStr` is now dead code).
Empty arrays I'm pretty sure were always broken even before `SwiftSource` due to the counterintuitive behavior of `wrap` (namely, `wrap("[", "", "]") == ""` instead of returning `"[]"`). I didn't want to deviate too much from the underlying `wrap` behavior (since the behavior is relied-upon in places) so I just …
=> swift: Fix codegen with empty input objects / arrays

CHANGELOG.md, packages/apollo/src/commands/service/__tests__/__snapshots__/check.test.ts.snap, packages/apollo/src/commands/service/check.ts
The early return of the new (and improved) table UI was preventing the addition of the url.
=> fix url missing from service:check output

package-lock.json, packages/apollo/src/commands/service/__tests__/__snapshots__/list.test.ts.snap, packages/apollo/src/commands/service/list.ts
We always fetch list of services with a variant, so include it in the
CLI output
TODO:
=> Add variant to service list output

CHANGELOG.md, __fixtures__/starwars/schema.graphql, __fixtures__/starwars/schema.graphqls, __fixtures__/starwars/schema.json, packages/apollo-codegen-core/src/compiler/index.ts, packages/apollo-codegen-swift/src/__tests__/__snapshots__/codeGeneration.ts.snap, packages/apollo-codegen-swift/src/__tests__/codeGeneration.ts, packages/apollo-codegen-swift/src/codeGeneration.ts, packages/apollo/README.md, packages/apollo/src/commands/client/codegen.ts
Implement feature request described in https://github.com/apollographql/apollo-ios/issues/840
TODO:
=> Swift: Add flag to omit deprecated enum cases

jest.base.js, jest.config.js, package.json, packages/apollo-codegen-core/jest.config.js, packages/apollo-codegen-core/package.json, packages/apollo-codegen-flow/jest.config.js, packages/apollo-codegen-flow/package.json, packages/apollo-codegen-scala/jest.config.js, packages/apollo-codegen-scala/package.json, packages/apollo-codegen-swift/jest.config.js, packages/apollo-codegen-swift/package.json, packages/apollo-codegen-typescript/jest.config.js, packages/apollo-codegen-typescript/package.json, packages/apollo-graphql/jest.config.js, packages/apollo-graphql/package.json, packages/apollo-graphql/src/schema/__tests__/snapshotSerializers/astSerializer.ts, packages/apollo-graphql/src/schema/__tests__/snapshotSerializers/graphQLTypeSerializer.ts, packages/apollo-graphql/src/schema/__tests__/snapshotSerializers/selectionSetSerializer.ts, packages/apollo-language-server/jest.config.js, packages/apollo-language-server/package.json, packages/apollo-tools/jest.config.js, packages/apollo-tools/package.json, packages/apollo-tools/src/__tests__/buildServiceDefinition.test.ts, packages/apollo-tools/src/__tests__/snapshotSerializers/astSerializer.ts, packages/apollo-tools/src/__tests__/snapshotSerializers/graphQLTypeSerializer.ts, packages/apollo-tools/src/__tests__/snapshotSerializers/index.ts, packages/apollo-tools/tsconfig.json, packages/apollo/jest.config.js, packages/apollo/package.json
Semi-dependent upon #1611, though this could be split out to be its own set of changes independent of said PR.
This PR introduces a base Jest config from which all projects extend. It also simplifies the current config, as many options that were specified within each package were actually just the defaults that Jest provides.
This approach is a boon for maintainability of the configuration of this repo, and aligns with the approach that [`apollo-server`](https://github.com/apollographql/apollo-server/blob/master/jest.config.base.js) has taken.
TODO:
=> Unify and simplify jest config

CHANGELOG.md, packages/apollo/src/commands/client/check.ts, packages/apollo/src/commands/client/push.ts, packages/apollo/src/commands/service/__tests__/__snapshots__/list.test.ts.snap, packages/apollo/src/commands/service/check.ts, packages/apollo/src/commands/service/list.ts
Specifically, replace all instances of chalk.blue with chalk.cyan, which
is more readable in dark mode (the green color we use is basically
unreadable in light mode anyway)
Additionally, this changes some spacing of the service:list command to
allow users to see the URL to navigate to more obviously.
TODO:
=> Modify styling of CLI output

packages/apollo-language-server/src/errors/validation.ts, packages/apollo/src/Command.ts, packages/apollo/src/commands/client/codegen.ts
Currently, if you write an operation that throws an error in the validation step of codegen while in `--watch` mode, the watching will stop.
This PR changes a couple things to prevent that.
1. instead of `throw`ing an error in the validation step, we use the error logger from `apollo-language-server`.
2. Changes the error logger that the CLI sets from using `this.error` (which exits with a 1 code) to `console.error`.
3. Updates the watch mode function to catch thrown errors properly, as well as printing how many files are written.
TODO:
=> Fix thrown errors breaking out of --watch mode

packages/apollo/src/commands/client/codegen.ts
The name used in this parameter's help appears to be the previous version of the flag which is listed directly below this in the source (`tsFileExtension`).
=> Adjust misnamed `fileExtension` to `tsFileExtension` in help.

CHANGELOG.md, packages/apollo-language-server/src/project/client.ts
Currently, if you click on the Apollo logo on the status bar, stats for the project you're working with are supposed to show, to confirm the config was setup properly and the extension has loaded.
If you're setting up a client project and using a `localSchemaFile` though, the stats will fail to load unless there is a service `name` also provided, which isn't required.
This removes the check in the stats loading function that forced a client to have a `client.service.name` even if not using graph manager to load the schema.
TODO:
=> Fix client localSchemaFile for vscode stats command

CHANGELOG.md, packages/apollo-codegen-swift/src/__tests__/__snapshots__/codeGeneration.ts.snap, packages/apollo-codegen-swift/src/codeGeneration.ts, packages/apollo/src/commands/client/__tests__/__snapshots__/generate.test.ts.snap
Adding explicit type annotations for `operationDefinition`, `operationName`, and `possibleTypes` to help out Swift compile times.
TODO:
=> [Swift Codegen] Adding some explicit type annotations

CHANGELOG.md, packages/apollo-graphql/src/schema/__tests__/buildSchemaFromSDL.test.ts, packages/apollo-graphql/src/schema/buildSchemaFromSDL.ts
Fixes https://github.com/apollographql/apollo-tooling/issues/1617
Updated buildSchemaFromSDL to handle enums with a value of 0. Previously, when an enum had a value of 0, the name would be used as the enum value.
Added a unit test to ensure 0 is parsed correctly.
TODO:
=> Fixes #1617: Federation Enum not parsing value 0

CHANGELOG.md, packages/apollo-language-server/src/engine/index.ts, packages/apollo-language-server/src/project/client.ts, packages/apollo-language-server/src/providers/schema/engine.ts, packages/apollo/src/commands/client/check.ts, packages/apollo/src/commands/client/codegen.ts, packages/apollo/src/commands/client/download-schema.ts, packages/apollo/src/commands/client/push.ts, packages/apollo/src/commands/service/__tests__/check.test.ts, packages/apollo/src/commands/service/__tests__/list.test.ts, packages/apollo/src/commands/service/check.ts, packages/apollo/src/commands/service/delete.ts, packages/apollo/src/commands/service/download.ts, packages/apollo/src/commands/service/list.ts, packages/apollo/src/commands/service/push.ts
Right now, the messaging in the CLI and language-server is split between "Engine" and "Apollo Graph Manager". 
This PR updates the logged output to be all "Apollo Graph Manager"
TODO:
=> Rename "Engine" to "Apollo Graph Manager" in ouput

CHANGELOG.md, packages/apollo-language-server/src/providers/schema/endpoint.ts
Two of the most common errors that people encounter in the CLI and VS Code extension revolve around introspecting of schemas.
1. Unless an API key, endpoint, or `localSchemaFile` are provided, the language server relies on the default endpoint `http://localhost:4000`. If there is no server running there, it will 404. If the user _has_ a service to run there (or anywhere else) but forgets to start it up, it will also 404. This PR adds an error for both of those cases. If the URL IS the default one, it will provide info about that. 
2. If users are trying to introspect a url without authentication (or some other cases) the endpoint will return an HTML response, which the CLI can't parse. This PR adds an error mentioning auth and potentially invalid URLs.
TODO:
\*Make sure changelog entries …
=> Add errors for 404 and HTML responses

packages/apollo-language-server/src/providers/schema/index.ts
This PR reverts a change to the provider order made in https://github.com/apollographql/apollo-tooling/commit/bb06f49e79f721cb511ef1b5a8880f6d50d6b0d3
This change doesn't work with use of `localSchemaFile`s on service projects, since there is almost always a default url in the config. So the localSchemaFile option won't be hit.
TODO:
=> Revert order change of service schema providers

CHANGELOG.md, packages/apollo-codegen-swift/src/__tests__/__snapshots__/codeGeneration.ts.snap, packages/apollo-codegen-swift/src/codeGeneration.ts, packages/apollo-codegen-swift/src/language.ts
Implement [feature request](https://github.com/apollographql/apollo-ios/issues/562) to add documentation to input structs' generated constructors.
Generates documentation of the form:
```
/// - Parameters:
///   - someUndocumentedField
///   - someDocumentedField: This field has a documentation comment. When it is really long,
/// it wraps like this.
```
The way the text wraps is admittedly not ideal, but I couldn't think of a good way to make it wrap like this:
```
///   - someDocumentedField: This field has a documentation comment. When it is really long,
///                          it would be nice if it wrapped like this.
```
TODO:
=> [Swift] Add documentation to input structs' init

CHANGELOG.md, package-lock.json, packages/apollo-env/package.json
This PR is in response to https://github.com/apollographql/apollo-server/issues/3580. Currently, dependents of `apollo-env` can expect TS build errors if `@types/node-fetch` isn't included transitively. This affects the entire `apollo-server-*` family via `apollo-server-core`, as seen in this dependency tree:
```
apollo-example@1.0.0
└─┬ apollo-server-express@2.9.15
└─┬ apollo-server-core@2.9.15
├─┬ @apollographql/apollo-tools@0.4.2
│ └── apollo-env@0.6.0 
└─┬ apollo-engine-reporting@1.4.13
└─┬ apollo-graphql@0.3.6
└── apollo-env@0.6.0  deduped
```
The build error when trying to install `apollo-server-express` in a typescript project:
```
% npx tsc
node_modules/apollo-env/lib/fetch/fetch.d.ts:6:195 - error TS7016: Could not find a declaration file for module 'node-fetch'. …
```
=> Add @types/node-fetch to apollo-env deps since they are exported

CHANGELOG.md, packages/apollo-graphql/src/__tests__/__snapshots__/operationId.test.ts.snap, packages/apollo-graphql/src/__tests__/operationId.test.ts, packages/apollo-graphql/src/index.ts, packages/apollo-graphql/src/operationId.ts, packages/apollo/README.md, packages/apollo/src/commands/client/extract.ts, packages/apollo/src/utils/getOperationManifestFromProject.ts
Fixes #1099
Adds a flag `--[no]-preserveStringAndNumericLiterals` to `client:extract`
that controls whether literals are preserved in extracted queries. Prior to
this flag, object and list literals were already preserved; that's unaffected
by this change.
As noted in the linked issue, there are a few reasons to do this, but generally
they boil down to relying on the extracted queries for some functionality, and
literals in the queries controlling important behavior (e.g. generating mock data
for queries might rely on literal args).
A flag is preferred to changing the behavior outright since older clients likely
rely on the current behavior.
TODO:
=> Support disabling literal stripping when extracting operations.

CHANGELOG.md, packages/apollo-language-server/src/config/loadConfig.ts, packages/apollo-language-server/src/project/client.ts, packages/apollo-language-server/src/providers/schema/endpoint.ts, packages/apollo-language-server/src/providers/schema/index.ts, packages/apollo/src/Command.ts, packages/apollo/src/utils/validateHistoricParams.ts, packages/vscode-apollo/src/utils.ts
=> Update shortlinks to use go.apollo.dev

CHANGELOG.md, packages/apollo-language-server/src/graphqlTypes.ts, packages/apollo/src/commands/service/check.ts
Right now, `apollo service:check` for federated services expects a specifically shaped error message from composition errors, but not all errors are the expected shape. When that happens, we are not formatting the errors properly for display, and users are seeing a cryptic error about an inconsistent number of cells in the display table. This PR aims to fix that by displaying unformatted (unexpected) errors separately from the ones we can recognize and format.
before:
after: 
TODO:
=> Fix display of unformatted errors in composition

CHANGELOG.md, package-lock.json, package.json, packages/apollo/package.json, packages/apollo/src/commands/client/download-schema.ts, packages/apollo/src/commands/service/download.ts
resolves #1788 
Previously, the CLI couldn't download schemas in `apollo service:download` or `apollo client:download-schema` when the path in the `OUTPUT` didn't exist.
This PR aims to add the ability to create a path given in the `OUTPUT` and to save the outputted schema to that path :)
TODO:
=> Add ability to define schema download output path that doesn't exist yet

CHANGELOG.md, packages/apollo-language-server/src/project/base.ts
This PR aims to fix an issue where some users are pushing client code that errors because the error notifying users of duplicate client operation names doesn't exit appropriately.
the previous error, just told users that duplicate operations aren't permitted in client projects, but never actually _enforced_ that as it should have. This PR should fix that behavior.
TODO:
=> Make duplicate operations error a failing error

packages/apollo-language-server/src/engine/index.ts
Currently, the message we provide to users for querying a service that
does not exist (or that they do not have access to) looks up the service
ID from the key rather than using the actual variable that it passed to
AGM when looking it up. This changes such messages to always use the
actual service ID that they were searching for.
Specifically, this is to support user tokens, where the graph in
question may not, in fact, be in the key, but instead by provided by
apollo.config.js
TODO:
=> Change non-existent service message to be correct

packages/apollo/src/commands/client/check.ts, packages/apollo/src/commands/client/push.ts, packages/apollo/src/commands/service/check.ts, packages/apollo/src/commands/service/delete.ts, packages/apollo/src/commands/service/list.ts, packages/apollo/src/commands/service/push.ts, packages/apollo/src/utils/errors.ts
This updates the error message that occurs when a config.service.name is
required in order to execute a command. Before this commit, there were
two distinct messages that were used in commands to communicate this
error to the user, which were slightly different in their wording. This
updates the wording to provide an explanation as well as next steps on
how to remedy the issue. Additionally, it uses the `CLIError` class in
order to print out an error in a "friendly" way without a stack trace,
as recommended by the @oclif/errors package we are using: https://oclif.io/docs/commands#thiserrormessage-string--error-options-code-string-exit-number
For changelog entry, please see https://github.com/apollographql/apollo-tooling/pull/1849
TODO:
\*Make sure changelog entries note which project(s) …
=> Update "no service found to link..." error

CHANGELOG.md, packages/apollo-language-server/src/config/__tests__/loadConfig.ts, packages/apollo-language-server/src/config/loadConfig.ts, packages/apollo-language-server/src/graphqlTypes.ts, packages/apollo-language-server/src/project/base.ts, packages/apollo-language-server/src/providers/schema/engine.ts, packages/apollo/src/Command.ts, packages/apollo/src/commands/client/__tests__/check.test.ts, packages/apollo/src/commands/service/__tests__/check.test.ts, packages/apollo/src/commands/service/__tests__/publish.test.ts
This supports a more modern name for the API key and adds deprecation
messages for the (now legacy) ENGINE_API_KEY. Much in the same spirit
as #1849, the goal is to modernize our documentation to no longer use the out-of-date name
"engine". This also modifies tests to support the new version and adds a
test that ensures an error is thrown when a user sets _both_ keys.
=> [GM-833] Add support for APOLLO_KEY; deprecate ENGINE_API_KEY

packages/apollo-language-server/src/graphqlTypes.ts, packages/apollo/src/commands/service/check.ts
When using the GitHub integration, it's often recommended to run
service:check && echo "ignoring output" because GH status will be
updated by the command. Adding this option makes using the command with
GH integration cleaner by exiting with 0 on all schema errors.
Fixes #1852 
TODO:
=> service:check Add ignoreFailures flag

packages/apollo-language-server/src/config/loadConfig.ts
The message that appeared for users using `ENGINE_API_KEY` was not actionable before this change. This updates the message to suggest using `APOLLO_KEY` in lieu of `ENGINE_API_KEY` :)
I don't _think_ this kind of change really necessitates a CHANGELOG entry, but happy to add one if requested.
TODO:
=> Update deprecation message of ENGINE_API_KEY to include alternative of APOLLO_KEY

packages/apollo/src/commands/service/push.ts
When running `npx apollo service:push --help`, there is no entry for `--variant`, due to `hidden: true` being used in the options for the flag (#1849). This PR removes the `hidden: true`.
TODO:
=> Remove "hidden: true" from variant flag in service:push

.circleci/config.yml, CHANGELOG.md, packages/apollo-codegen-core/package.json, packages/apollo-codegen-flow/package.json, packages/apollo-codegen-scala/package.json, packages/apollo-codegen-swift/package.json, packages/apollo-codegen-typescript/package.json, packages/apollo-env/package.json, packages/apollo-graphql/package.json, packages/apollo-language-server/package.json, packages/apollo-language-server/src/graphqlTypes.ts, packages/apollo-tools/package.json, packages/apollo/README.md, packages/apollo/package.json, packages/vscode-apollo/package.json
With CircleCI dropping artifcats after 30 days soon, we want to move all releases to publish to GitHub releases as a more stable storage spot for downloads of builds. This PR tries out the changes to the shared ci-cd orb to add publishing to GitHub Releases
=> try out github release via orb

CHANGELOG.md, package-lock.json, packages/apollo-codegen-core/src/compiler/legacyIR.ts, packages/apollo-codegen-core/src/serializeToJSON.ts, packages/apollo-language-server/package.json, packages/apollo/src/commands/client/__tests__/__snapshots__/generate.test.ts.snap, packages/apollo/src/generate.ts
Hopefully resolves #1909 
The legacy IR contains information that codegen in swift needs to
work properly. When building the json-modern target, I didn't
account for everything that was dropped from the original json
output :sad:. This commit changes the json-modern codegen target
so it uses the legacy IR generation with the exposeTypeNodes option
set to true (which passes it to the new ir codegen since legacy
uses that under the hood lol).
TODO:
=> Change json-modern target to use legacy IR

CHANGELOG.md, packages/apollo-language-server/src/project/base.ts
If there is a directory named like a file, meaning the path ends in something like `.ts`, then the glob in an apollo config could pick up directories. We need to make sure we are trying to open a file before we run `readFileSync` or having this weirdly named path will cause the CLI and VSCode Extension to crash.
FWIW We're seeing this in AGM right now because [Cypress](https://www.cypress.io/) creates screenshots for tests with the test filename as the directory name in the screenshots directory.
TODO:
=> Fix CLI and VSCode from crashing when discovering a path named like a file

CHANGELOG.md, packages/apollo-codegen-swift/src/__tests__/__snapshots__/codeGeneration.ts.snap, packages/apollo-codegen-swift/src/codeGeneration.ts, packages/apollo/src/commands/client/__tests__/__snapshots__/generate.test.ts.snap
A workaround for [iOS #230](https://github.com/apollographql/apollo-ios/issues/230) - the way that Swift allocates `static lets` was basically eating through memory that it shouldn't been. This transitions to using a computed `static var` instead, which should alleviate the problem. 
~I did look into just making it a computed var but there were some...complications... with the formatting that I wasted far too much time on trying to make work, and this achieves the same effect with a more minimal change.~ Got it working as a computed `var` after stepping away from the code for a weekend.
=> Swift: Make selections a var instead of a let

CHANGELOG.md, packages/apollo-language-server/src/document.ts, packages/apollo-language-server/src/project/base.ts, packages/vscode-apollo/package.json, packages/vscode-apollo/src/languageServerClient.ts, packages/vscode-apollo/syntaxes/graphql.ex.json
TODO:
This PR adds support for the Elixir language on vscode. Screenshot of it in action below:
Thanks to @rkolpakov for the bulk of the work.
=> Add vscode support for Elixir

packages/apollo-language-server/src/document.ts, packages/apollo-language-server/src/graphqlTypes.ts, packages/apollo/src/commands/client/codegen.ts
resolves #1897 
During document parsing, syntax errors are silently
added to the document, but errors are never thrown.
This PR checks at the _command-level_ for these errors
and if they exist, prints them to the user.
I didn't want to change at the document setup level, because
I have a feeling the silent erroring was intention for the sake
of the operation registry or something. So I added in an error
where it was immediately causing an issue, in the client
codegen command.
TODO:
=> Fix silent codegen errors on syntax errors

CHANGELOG.md, package-lock.json, packages/apollo/package.json, packages/apollo/src/__tests__/git.test.ts, packages/apollo/src/git.ts
This PR aims to fix a security issue where the CLI would send some users' git credentials to Apollo Graph Manager (AGM).
> It's important to note that although this security risk was identified, **we do not believe that any personal data was ever leaked through this**. This issue was identified internally and has been fully dealt with on the backend before this change. 
Few users were affected by this issue, and if your account was affected by this, you will also receive an email informing you.
Once the changed in this PR is released, we recommend all users upgrade to the newest version of the CLI to prevent sending any unnecessary sensitive information.
Apollo Graph Manager attempts to link back to a PR or a repository on GitHub or BitBucket from the Graph Manager's history page. This …
=> Prevent cli from sending git credentials

CHANGELOG.md, apollo.config.js, packages/apollo-language-server/src/config/__tests__/config.ts, packages/apollo-language-server/src/config/__tests__/loadConfig.ts, packages/apollo-language-server/src/config/config.ts, packages/apollo-language-server/src/engine/index.ts, packages/apollo-language-server/src/engine/operations/checkPartialSchema.ts, packages/apollo-language-server/src/engine/operations/checkSchema.ts, packages/apollo-language-server/src/engine/operations/listServices.ts, packages/apollo-language-server/src/graphqlTypes.ts, packages/apollo/src/Command.ts, packages/apollo/src/commands/service/__tests__/list.test.ts, packages/apollo/src/commands/service/check.ts, packages/apollo/src/commands/service/list.ts
Currently the CLI has configuration (via `engine.frontend` in a config file or
the --frontend flag to a few commands) to control what Engine frontend the user
is using. This is primarily set by Apollo employees using staging servers. This
is in addition to setting `engine.endpoint` to control which GraphQL server it
talks to.
This is used for two things:
- passing arguments to a couple ServiceMutation fields
- printing links in `services:list`
As of recently, this no longer is needed:
- those ServiceMutation fields now ignore the `frontend` argument and just use
the correct frontend for the server processing them
- we expose a Query.frontendUrlRoot field that `services:list` can use
So this change completely removes recognition of this config field as well as
the flag. (Note that it is …
=> [AR-1691] The CLI does not need to know the frontend URL

CHANGELOG.md, packages/vscode-apollo/package.json
It was registered under the wrong name since its introduction in #840.
=> vscode-apollo: Fix 'Apollo: Show Status' command

CHANGELOG.md, packages/apollo-language-server/src/providers/schema/file.ts
=> Fix definition navigation for vscode using localSchemaFile (missing file url)

package-lock.json, package.json, packages/apollo/README.md, packages/apollo/package.json
The default value of $COLUMNS in `oclif-dev readme` is 120, so we hardcode this
so that we don't reformat the whole README whenever a developer does a release
from a narrower shell.
This reverts the reformatting done in the previous release, which implies that 120 was the correct value to choose.
=> Hardcode $COLUMNS when running oclif-dev readme

CHANGELOG.md, apollo.config.js, packages/apollo-language-server/src/graphqlTypes.ts, packages/apollo/src/commands/service/check.ts, packages/apollo/src/git.ts
This will allow users to pass in a --branch or --author to a call of
service:check, which will provide a means to group changes in the UI for
schema checks
TODO:
=> Support flags for branch and author in s/check

CHANGELOG.md, packages/apollo-codegen-core/src/compiler/index.ts, packages/apollo-codegen-swift/src/__tests__/__snapshots__/codeGeneration.ts.snap, packages/apollo-codegen-swift/src/codeGeneration.ts, packages/apollo/src/commands/client/__tests__/__snapshots__/generate.test.ts.snap, packages/apollo/src/commands/client/__tests__/fixtures/queryWithFragments.graphql, packages/apollo/src/commands/client/__tests__/generate.test.ts, packages/apollo/src/generate.ts
I took over the rest tasks (adding tests) of #1431.
Could you make sure that it is enough?
- Rebased onto the current HEAD of `master` branch
- Modified existing tests and updated snapshots
- Confirmed the tests passed in my local env
- However it looks flaky so I ran tests with `node node_modules/.bin/jest -t generate -i --no-cache` to exclude unchanged.
TODO:
=> Add tests for "swift: Fix --operationIdsPath option" #1431

CHANGELOG.md, packages/apollo-codegen-core/src/__tests__/__snapshots__/jsonOutput.ts.snap, packages/apollo-codegen-core/src/__tests__/jsonOutput.ts, packages/apollo-codegen-core/src/compiler/index.ts, packages/apollo-codegen-core/src/compiler/legacyIR.ts, packages/apollo-codegen-core/src/serializeToJSON.ts, packages/apollo/src/commands/client/__tests__/__snapshots__/generate.test.ts.snap
This commit adds new top level properties called `unionTypes` and `interfaceTypes`, to the `json-modern` exported IR. These properties list all unions and their types, as well as all interfaces and their implementing types.
=> Add `unionTypes` and `interfaceTypes` to the `json-modern` IR

packages/apollo-language-server/src/engine/index.ts, packages/apollo-language-server/src/graphqlTypes.ts, packages/apollo/src/__tests__/git.test.ts, packages/apollo/src/git.ts
This PR updates `sanitizeGitRemote()` to:
- safelist `bitbucket.org` instead of `bitbucket.com`
- set `info.token` to empty string, as it may also appear in HTTP/S remote URLs
TODO:
=> Update sanitizeGitRemote() to safelist bitbucket.org, and to set GitUrl.token to empty string

CHANGELOG.md, packages/apollo-graphql/src/__tests__/__snapshots__/operationId.test.ts.snap, packages/apollo-graphql/src/__tests__/operationId.test.ts, packages/apollo-graphql/src/index.ts, packages/apollo-graphql/src/operationId.ts, packages/apollo-graphql/src/transforms.ts
Rename `defaultEngineReportingSignature` to `defaultUsageReportingSignature`;
the old name continues to be exported as well.
This is part of the effort to remove the name Engine from our APIs. See
https://github.com/apollographql/apollo-server/pull/4453
=> apollo-graphql: Rename defaultEngineReportingSignature

CHANGELOG.md, packages/apollo/src/__tests__/git.test.ts, packages/apollo/src/git.ts
Now that the backend properly sanitizes remote URLs, we don't have to worry about GitLab remote URLs containing sensitive information. This PR adds GitLab back to the safelist for remote URLs in `sanitizeGitRemote()`.
TODO:
=> Allow GitLab remote URLs in sanitizeGitRemote()

CHANGELOG.md, packages/apollo/src/commands/service/check.ts, packages/apollo/src/commands/service/push.ts
Add `--author` and `--branch` to `service:push` to match `service:check`,
and `--commitId` to both. Makes it easy to override this information, as
CI environments can provide erroneous information.
=> [GM-1636] cli: service:{check,push} --commitId

CHANGELOG.md, packages/apollo-codegen-swift/src/__tests__/__snapshots__/codeGeneration.ts.snap, packages/apollo-codegen-swift/src/__tests__/codeGeneration.ts, packages/apollo-codegen-swift/src/codeGeneration.ts
Key is AbcCTA, which get's converted by singularize to structName: AbcCTum (this is already not great, but not the bug causing compilation issues)
The key is used to create the structName.
In this place the property (abcCtum) was being used instead which made: AbcCtum (AbcCTum and AbcCtum don't match, notice the T vs t)
CC @designatednerd
=> Update codegen to work for AbcCTum (Was converting to AbcCtum)

CHANGELOG.md, packages/apollo-codegen-swift/src/__tests__/__snapshots__/codeGeneration.ts.snap, packages/apollo-codegen-swift/src/codeGeneration.ts
Splits the appending of fragments to the query document into separate
sub expressions to fix an issue where a query that references lots of fragments
causes the Swift type checker to fail with the following message:
```
error: the compiler is unable to type-check this expression in reasonable time; try breaking up the expression into distinct sub-expressions
```
TODO:
=> Swift Codegen: Split up appending of fragments to query document

packages/apollo-language-server/src/graphqlTypes.ts
Same as usual updates with `npm run client:codegen`.
=> Update codegen types from Apollo Registry

.circleci/config.yml
The "VS Code" testing that we have setup, while something that has been implemented for a while, is relatively under-used; there is only a single test today.
That testing framework was put in place some time ago, using a package and a technique that is now-deprecated and should be upgraded to a new pattern:
https://code.visualstudio.com/api/working-with-extensions/testing-extension#migrating-from-vscode
Unfortunately, something about the existing `vscode` extension's technique of automatically downloading VSCode versions from their infrastructure just stopped working randomly with no changes at all to the dependencies of this package.  I found this through a long git-bisect process which revealed that even old commits years ago and even the commit that first introduced the testing are now …
=> ci: Disable single VS Code test because of failing VS Code test harness.

CHANGELOG.md, package-lock.json, package.json, packages/apollo-graphql/package.json, packages/apollo-graphql/src/utilities/createHash.ts
Related to #2274, which removes a dependency on `apollo-env` which transitively required this package (presumably, unconfirmed but I will validate).
This also adds typings to the require() statements for the respective modules.
TODO:
=> Install missing `sha.js` dependency

package-lock.json
npm 7 seems to be better at identifying malformed package-lock.json files
and is suggesting this change that removes `apollo-graphql` (our package)
from being a package that is depended on by a package called `which-module`,
which is definitely not a dependency of that package.
This most likely happened in a malformed conflict resolution attempt since
`which-module` has not been updated since before `apollo-graphql` came into
existence and since it has [No Dependencies] itself:
[No Dependencies]: https://www.npmjs.com/package/which-module?activeTab=dependencies
=> chore: update package-lock.json to fix incorrect nesting of `apollo-graphql`

CHANGELOG.md, packages/apollo/README.md, packages/apollo/package.json, packages/apollo/src/Command.ts, packages/apollo/src/commands/service/check.ts, packages/apollo/src/commands/service/delete.ts, packages/apollo/src/commands/service/download.ts, packages/apollo/src/commands/service/list.ts, packages/apollo/src/commands/service/push.ts, packages/apollo/test-utils/setup.js
This PR deprecates the `apollo` CLI `service:*` commands by:
- Printing (to `stderr`) deprecation messages for all runtime `apollo service:*` commands (pointing people to the [Rover migration guide](https://go.apollo.dev/t/migration))
- Printing deprecation messages when using `apollo service:*` CLI `help` commands
- Labelling all `service:*` commands as deprecated in the `README`
`service:*` functionality has not been removed since this PR will be rolled out in a patch release. After Rover is officially released, we’ll push out a new major version of `apollo` that fully removes the `service:*` commands.
Reference: https://github.com/apollographql/rover/issues/471
=> Deprecate apollo CLI service:* commands

CHANGELOG.md, packages/apollo-graphql/src/schema/__tests__/transformSchema.test.ts, packages/apollo-graphql/src/schema/transformSchema.ts
This change fixes `transformSchema`, which previously left directives as-in after transforming types. This meant that Input types used in directive arguments would appear duplicated in the schema. It now recreates schema directives and their arguments like it does with named schema types.
Fixes #2162
TODO:
=> fix(apollo-graphql): support complex directive args

CHANGELOG.md, package-lock.json, packages/apollo-tools/package.json, packages/apollo-tools/src/buildServiceDefinition.ts, packages/apollo-tools/src/index.ts, packages/apollo-tools/tsconfig.json
As far as I can tell, the only use `@apollographql/apollo-tools` makes
of `apollo-env` is the ability to use `Array.flat` in pre-12 Node. Now,
we probably should just make this whole repo require Node 12 like we are
doing for Apollo Server 3. But a simpler way to break this dependency is
to just implement a single-level Array.flat ourselves. (The calls to
Array.flat do not take advantage of its ability to flatten more than one
level of nested array.)
This will allow us to stop installing polyfills in Apollo Server 3 (see
apollographql/apollo-server#2634).
=> apollo-tools: remove dependency on apollo-env

packages/apollo/src/commands/client/codegen.ts
Removal of usage of tty npm package as it's been removed from npm due to potential security issues. 
https://www.npmjs.com/package/tty
TODO:
=> Remove TTY package due to security vulnerability

CHANGELOG.md, packages/apollo-graphql/src/__tests__/transforms.test.ts, packages/apollo-graphql/src/index.ts
GraphQL execution requests can include PII. At Indeed we have need of a mechanism to sanitize requests of PII in order to maintain GDPR and CCPA requirements. I'm certain many other companies have this need, and expect this to also be useful for companies requiring HIPPA compliance.
The existing hideStringAndNumericLiterals and hideLiterals functions look to be well suited for this purpose. Here I've exported these functions, along with printWithReducedWhitespace which is a nice companion to both. I've updated the existing test for `hideLiterals` to cover more scenarios and added a test for `hideStringAndNumericLiterals`.
=> Export useful sanitizing functions: printWithReducedWhitespace, hideStringAndNumericLiterals and hideLiterals

CHANGELOG.md, package-lock.json, packages/apollo-graphql/src/schema/__tests__/buildSchemaFromSDL.test.ts, packages/apollo-graphql/src/schema/buildSchemaFromSDL.ts
updates buildSchemaFromSDL to pass through applied directives on the `schema` definition node.
TODO:
=> fix(apollo-graphql): Preserve directive usages on SchemaDefinition nodes

CHANGELOG.md, packages/apollo-codegen-core/src/__tests__/__snapshots__/jsonOutput.ts.snap, packages/apollo-codegen-core/src/compiler/index.ts, packages/apollo-codegen-core/src/utilities/__tests__/graphql.test.ts, packages/apollo-codegen-core/src/utilities/graphql.ts, packages/apollo-language-server/src/graphqlTypes.ts, packages/apollo-language-server/src/index.ts, packages/apollo-language-server/src/utilities/index.ts
The `withTypenameFieldAddedWhereNeeded` utility in `apollo-language-server` was updated in #1286 to make sure `__typename`'s are added to inline fragments, when used by commands like `client:push`. The `apollo-codegen-core` package currently uses its own copy of `withTypenameFieldAddedWhereNeeded` however, which was not updated. This means that operations can be registered (in Apollo's operation registry) via `client:push` that don't line up with the operations output by codegen.
This commit adjusts the `apollo-codegen-core` package to use the same `withTypenameFieldAddedWhereNeeded` function as `apollo-language-server` (which is already a dependency of codegen), to make sure the operations output from codegen line up with the operations pushed via `client:push`.
=> Align codegen and language server inline fragment __typename use

packages/apollo/README.md
We'll add more details soon but this should help give people that are thinking about adopting `apollo` into their workflows a heads up.
=> Mention upcoming deprecation plans in the README

CHANGELOG.md, package-lock.json, packages/apollo-tools/package.json
`@apollographql/apollo-tools` is using `graphql` without declaring it as a dependency, this causes issues under strict dependency environments (Yarn PnP) and causes it to rely on hoisting to hopefully place it in a accessible location which is not guaranteed.
Fixes https://github.com/apollographql/apollo-tooling/issues/1680
TODO:
=> fix(apollo-tools): add undeclared peer dependency graphql

CHANGELOG.md, package-lock.json, packages/apollo-language-server/package.json, packages/apollo-language-server/src/__tests__/format.test.ts, packages/apollo-language-server/src/format.ts
There is really no strong need for `moment` to a dependency of `apollo-language-server` when it is used just to calculate durations in milliseconds. A simple constant will suffice instead.
Also added some tests to prove that this change works but is by no means exhaustive.
Related: https://github.com/apollographql/apollo-tooling/issues/2323.
TODO:
=> Remove `moment` as a dependency for `apollo-language-server`

.changeset/chilled-yaks-refuse.md, packages/apollo-language-server/src/graphqlTypes.ts, packages/apollo/src/Command.ts, packages/apollo/src/commands/client/codegen.ts
Related: https://github.com/apollographql/apollo-tooling/issues/2614
This change officially deprecates the codegen utility in the Apollo CLI. The recommendation going forward is to use the `graphql-code-generator` utility.
For iOS (for which there is no existing replacement): patch fixes will still be entertained and released on the v2.x line, but no further development will be done unless it's necessary. Apollo iOS intends to release their own codegen in the relatively near future.
While we do encourage moving away from the CLI as quickly as possible, I'm sympathetic to the fact that a change might not be feasible right away. I've included the `--suppressDeprecationWarning` flag in order to silence the console output when running the `client:codegen` command.
I haven't added tests for …
=> Deprecate `client:codegen` command
